### ISSUE TITLE
Specify Manure Type in Soil and Crop Manure Application Requests

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1044]
**Is your feature request related to a problem? Please describe.**
The type of Manure (i.e. solid or liquid) is an important factor for consideration in Manure application. Currently the manure application is based on N & P alone. The form of manure (specifically, how much water is associated with the manure nutrients and solids) is an important factor to consider in manure application and in soil nutrient cycling. Thus, we need to be able to specify the form of the manure when the Soil and Crop module requests manure from the Manure Module. 

**Describe the solution you'd like**
I would like to add a variable that indicates the manure type to the Manure-Field connector request from the soil and crop module so that the Manure Module can only provide the nutrients from the relevant manure streams for application. 

**Describe alternatives you've considered**
An alternative would be to specify a range of values of acceptable Total Solid fractions but I think this is too specific and will be more difficult to track manure masses in the Manure Module

**Additional context**

**Comment by Isgotkowitz** [comment]
@krb78 am I correct in thinking that if manure is applied to a field with some sort of machinery, it has to be at or below some threshold of liquidity? If so, maybe an acceptable quick fix for this issue would be to assume that all manure coming through the Manure-Field connector is liquid?

**Comment by krb78** [comment]
Ahhh... well not quite because we just need a different implement to spread the solid manure (manure that has been composted is a good example). We have spoken so much about manure from slurry or lagoon systems being spread, injected, and side-dressed in our recent conversations, but many farms will have some type of solid manure (usually from calves) that needs to be spread in a solid form.

**Comment by Isgotkowitz** [comment]
Maybe addressing this issue would be a good opportunity to change the way that the Crop and Soil module thinks about manure applications, which could in turn be part of a fix to this problem? Right now Field only thinks about it as a minimum amount of nitrogen and a minimum amount of phosphorus that need to be in the application - but I don't know any reasons why it should have to stay this way. Perhaps a better method would be to let users specify the dry matter mass / ha they want, and whether it should be solid or liquid, and let that determine the manure application?

**Comment by krb78** [comment]
I don't know how much work that takes, but my thought from the very beginning of this has been that producers think about gallons of manure applied per acre so the closer we can get to that being the input, the better we'll be at getting the data from them and the closer RuFaS will be to approximating reality. I don't think dry matter mass/ha will alleviate the need to specify solid or liquid, right? Because a producer could know they are applying 6,000 gallons (at 5% DM slurry)/ha (and if I did my math right) this would be 22,909 kg manure/ha or 1,145 kg dry matter manure/ha - which is easy enough to do. But would RuFaS choose to apply the slurry or choose to apply 1,145 kg dry matter manure in the form of compost which would be 4,580kg of composted manure (at 25% DM) instead of the slurry we actually intended to apply? We would still need to specify solid vs liquid right? With the cutoff in DM for solid and liquid being ~8% DM

**Comment by krb78** [comment]
What I think I'm trying to say Ed is, I think your idea is a great one, if it's not too much work, but we probably still need to add in the solid v liquid component. :)

**Comment by KFosterReed** [comment]
Hey Ed! I just called Kaitlyn to clarify a few things in my mind and am going to share them here: 
1. We need to keep the current nutrient based methods for applying manure
2. We need to add a specification of manure type to the manure application method regardless of the whether or not #3 below happens
3. It would be great to add an option that allows the user to specify the manure application rate based on total manure mass (kg) but this should not replace the current nutrient based application methods. 


#3 is a nice to have but not a priority. For now, can we implement #2 and make an issue for #3?

**Comment by ltp23** [comment]
Hi Kristan, I have tried to implement option 2. I can create three separate manure pools that correspond to the three manure forms - liquid, slurry, and solid. When there is new manure produced, the nutrients will go to their respective pools. 

If we support this option for making manure type-specific nutrient requests by the crop and soil module, should we still support the current option for making generic requests that don't specify a manure type? If so, we would need some sort of an algorithm to decide which pool(s) or order between them to draw the manure from in the case of a generic request. 

On the other hand, for any manure-type specific request, if there isn't enough manure to meet the request, we would just return whatever is available for that specific type and the requester can then decide whether to make another request for a different type.

**Comment by KFosterReed** [comment]
Hi Loi! Thanks for getting started on this already! A couple of responses/comments:

1. We would like to keep the following pools: liquid, solid, and sludge. (slurry and liquid will be treated the same)
2. We do not want to maintain an option for generic requests - all requests will specify the type of manure. 
3. If there isn't enough manure available of the specific type requested, we would return the same information as currently sent to indicate there is not enough manure. Maybe we will add functionality in the future to supplement with other manure types but that will require more user inputs and more logic that we do not want to implement now.

**Comment by Isgotkowitz** [comment]
> 1. We need to keep the current nutrient based methods for applying manure

> gallons of manure applied per acre so the closer we can get to that being the input, the better we'll be at getting the data from them and the closer RuFaS will be to approximating reality

@KFosterReed @krb78 what about modifying the inputs so that the manure applications are specified in kg/ha instead of just kg, and Crop and Soil makes the total kg calculation on the fly? (This wouldn't be a difficult change to make, but obviously it can wait for V1.X if it just a nice-to-have.)

> 2. We need to add a specification of manure type to the manure application method regardless of the whether or not 3 below happens

Roger that. We can make an issue or possibly just add a task in this issue. It will not be a time intensive task to implement on the Crop and Soil side, but the sooner we can specify _exactly_ what the inputs should be the quicker it can happen.

Also I would like to confirm something: after this change is implemented, the information being passed _from_ Crop and Soil to Manure _will_ change, but the information being passed from Manure to Crop and Soil _will not_ change, correct?

**Comment by KFosterReed** [comment]
> > 1. We need to keep the current nutrient based methods for applying manure
> 
> > gallons of manure applied per acre so the closer we can get to that being the input, the better we'll be at getting the data from them and the closer RuFaS will be to approximating reality
> 
> @KFosterReed @krb78 what about modifying the inputs so that the manure applications are specified in kg/ha instead of just kg, and Crop and Soil makes the total kg calculation on the fly? (This wouldn't be a difficult change to make, but obviously it can wait for V1.X if it just a nice-to-have.)

In the case of total manure mass being used as the units for specifying manure applications, I don't have enough insight/knowledge to know if total kg or kg/ha would be better. Perhaps @krb78 and Eric Young what they think?
> 
> > 2. We need to add a specification of manure type to the manure application method regardless of the whether or not 3 below happens
> 
> Roger that. We can make an issue or possibly just add a task in this issue. It will not be a time intensive task to implement on the Crop and Soil side, but the sooner we can specify _exactly_ what the inputs should be the quicker it can happen.
> 
> Also I would like to confirm something: after this change is implemented, the information being passed _from_ Crop and Soil to Manure _will_ change, but the information being passed from Manure to Crop and Soil _will not_ change, correct?

Correct! Same information going to the Soil and Crop Module! I think the manure composition should be enough information to document application including what type of manure it is

**Comment by krb78** [comment]
Ok, I'm old and don't know how to reply like you guys are haha... but I think kg/acre or I suppose kg/ha is better than total kg! We think of crop needs in kg/ha (or kg/acre) so I think that data will be easier to get! Double check with Eric, but I think he'd agree! :)
