### ISSUE TITLE
Add option to use recycled water for pen manure cleaning

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1062]
**Is your feature request related to a problem? Please describe.**
The manure module ManureHandler class calculates the amount of water used to clean the pen and adds that to the manure mass. On many farms, most, if not all of this water is recycled from the manure management system so is not 'new' water that is added every day. This causes the total manure volume (especially for systems that use flushing for the pen cleaning) to be unrealistically large. 

**Describe the solution you'd like**
 I would like to add a '`water recycling fraction`' parameter to the manure handler configuration inputs so that we can only add the fraction of water that is not recycled to the manure management system and have a more realistic volume of manure. This '`water recycling fraction`' would be used in the ManureHandler class function `calc_cleaning_water_volume_in_main_barn()`. The equation would be updated to: 
`cleaning_water_volume = num_animals * self.config.cleaning_water_use_rate*(1-water_recycling_fraction)`

**Describe alternatives you've considered**
An alternative would be to update the values for the clearning water use rates directly. This would be easier now but would not allow us to distinguish between those farms that recycle water and those that don't in the future. 

**Additional context**

**Comment by ew3361zh** [comment]
@KFosterReed how is the `water recycling fraction` ascertained? 
Is it a constant? 
Or is it being populated based on some characteristics of the farm (e.g. certain manure handling/processing types being present on a farm would mean they would need to implement the fraction)?
Or some other way?

**Comment by KFosterReed** [comment]
> @KFosterReed how is the `water recycling fraction` ascertained? Is it a constant? Or is it being populated based on some characteristics of the farm (e.g. certain manure handling/processing types being present on a farm would mean they would need to implement the fraction)? Or some other way?

I don’t think there is a standard recycling fraction so my preference would be to just add it as a user input in the relevant manure handler options. For example, CBPB (compost bedded pack barns) and Open lots wouldn’t have water recycling but all other manure handler types could potentially have that as an option. The default value would be  0% for all methods. An alternative option would be to just make it an input at the manure management scenario input level. 

@krb78 do you have any thoughts as to where it makes more sense to have this input?

**Comment by krb78** [comment]
The most common recycling that occurs is 2 places: 1) the water in the plate cooler is used to provide drinking water or milking parlor wash water (but this would be in the EEE layer, not the manure module) and 2) if it is a flush dairy, the water used to flush is often recycled many times (some audits have shown water is used 4 times on a dairy farm with a flush system). 

I think we should make it just a "Y/N" user input in the manure management section and then in the EEE section (as that is built out/inputs are added). For people that choose flushing as the way they clean manure from alleys/holding pen/parlor we should have a question that asks if this water is recycled, if yes, we can assume it is recycled a maximum number of times (4) or an average number of times (2, for example) or we could ask how many times is it recycled (or what % of water used in manure management is from a recycled source on the farm). I think it makes sense to add this in as an input in the manure section as it is today. 

We should also add a question (this is the EEE question, but perhaps it could be added in the animal or feed section) that asks is drinking water from cows recycled from the plate cooler. In which case, I think Roohi's work can help illuminate how much less blue water needs to be pulled from ground/surface water locations to water the cows if we are using plate cooler water first. (As an FYI, fresh water is always used for the plate cooler because it is cold - you can't reuse the water for cooling the milk as it is already warmed up and therefore won't cool the milk).  

I'm not sure if I helped or just added to the confusion!

**Comment by KFosterReed** [comment]
Kaitlyn and I chatted about this earlier today and we agreed on a path forward. Instead of having a Y/N input and then a second input that describes the amount of recycling we will add an input that takes values between 0 and 1 to describe the fraction of recycled water that is used. Using this input, 0 will mean the same thing as No and any non-zero number will take the place of Y. 

I propose this new input variable be called something like `"cleaning_water_recycle_fraction"`  and be added to the `"manure_handler_configs"` section for each `"manure_handler_type"` that has a `"cleaning_water_use_rate"` input. 

In manure_handler_classes.py, this new input can be used in the `calc_cleaning_water_volume_in_main_barn` function. 

Instead of calculating the cleaning water volume as: 

 `cleaning_water_volume = num_animals * self.config.cleaning_water_use_rate`

we would do something like: 

`cleaning_water_volume = num_animals * self.config.cleaning_water_use_rate * (1-self.cleaning_water_recycle_fraction)`

@ew3361zh let me know if this makes sense or if you have any follow up questions! Thanks!!

**Comment by ew3361zh** [comment]
@KFosterReed and @krb78 I think this makes sense. Do you have a list of cleaning water recycle fractions for each manure handler type I can add to the input files?

**Comment by KFosterReed** [comment]
I think @krb78 is working on getting better references for these numbers but here is what I propose to start with: 

FLUSH_SYSTEM = 80%
    MANUAL_SCRAPING = 10%
    ALLEY_SCRAPER = 10%
    TILLAGE = 0%
    HARROWING = 0%

**Comment by krb78** [comment]
I think these are a great start! But yes, I have some emails out to some dairy experts in our friendly western states who can speak to this better than I can :)
