### ISSUE TITLE
Calcium and Phosphorus Requirements Being 'Complex' Datatype  

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1078]
The calcium requirement and min calcium standard comparison returned a 'TypeError' where it says '>' not supported between instances of 'float' and 'complex'. 

## Expected Behavior

The calculations of calcium requirement should return a real number instead of a complex data with a real and imaginary part.  

## Current Behavior

Here is a screenshot of the specific error that I ran into while running input files for farm 18 in cohort 2. 
![Screenshot 2023-12-25 at 4 01 46 PM](https://github.com/RuminantFarmSystems/MASM/assets/52800053/82972737-1f8a-487d-a047-5ddfc22a4205)

An example of the complex data is as follows. 
![Screenshot 2023-12-25 at 4 11 35 PM](https://github.com/RuminantFarmSystems/MASM/assets/52800053/69254330-6fa2-4bd2-bab3-562992b436b0)

## Possible Solution

I attempted to resolve this issue by using 'calcium_requirement.real' to convert the complex data to a real number. However, this attempt raised a new and different error. Please see below. 

![Screenshot 2023-12-25 at 4 06 15 PM](https://github.com/RuminantFarmSystems/MASM/assets/52800053/b4f5c5e6-e636-4db1-964a-26e248443f70)

Thus, I believe this issue requires further investigation. 

## Steps to Reproduce

1. Use this code `python3 main.py -c -v errors ` and make sure change the input file path to `'input/metadata/c2f18_metadata.json'` in the 'scenario_manager.py' file.  
2. Run the simulation and this error should occur. 
3.
4.

**Comment by jadamchick** [comment]
I just ran into this same error when trying to run cohort 2 farm 11. I tracked it down to the prefresh_day value (in the animal input .json), which was set as 60. When I lower it to 45, there is no error. 

I just checked and cohort 2 farm 18 (Haowen's farm in this issue) also has a prefresh_day value of 60. 

I didn't look any deeper to see what is actually happening to cause the error, but it seems to be related to this prefresh_day value. I'm working around it for now by lowering the value to 45 for c2f11. 

Maybe @JoeWaddell or @Ed731551 might have some insight? 

updated note Jan 12: With a prefresh_day value of 45, it (c2f11) runs sometimes but throws the error sometimes. When I lowered it to 30, it has run 6 times consecutively w/o any errors.

**Comment by tomhuhh** [comment]
Would like to hear more from others about their thoughts on this. Gonna to hold on to this for adding it to the Fixathon task list.

**Comment by JoeWaddell** [comment]
A little (ongoing) investigation work: so I looked at when it's failing, and it's because the animal has a `body_weight` of -614.97, which is only correct if the cow has been visiting the Wonka Factory, I guess.

Backtracking from there is a little trickier, because the only place I see where `prefresh_day` really comes into play is here:
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/f9c2fc2e-ef38-48cc-b6f3-628e4ce64c8d)

Stranger still, is I'm finding more cows with negative body_weight values prior to one large enough to crash the simulation! Still working my way backwards, but wanted to bring this up in case it helped others get to the bottom of what's going on.  Example below, using a temporary print statement and the debugger:
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/ccbcaf3d-d679-4f9f-bfcd-164475b571af)

# Adding more below #
Going upstream, finding that the average daily gain is running in reverse. Trying to understand why this is happening with the higher prefresh value, but once again, putting this here for posterity. Seems like somehow animals are going well past their gestation_length, though not sure why it's related to the prefresh_day val.
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/d318893f-0d8d-42d3-af6e-41b49bd64c32)

**Comment by jadamchick** [comment]
Thanks Joe! Good sleuthing! 
And maybe the prefresh day is a red herring, but lowering it did seem to effectively let me get around the error at least for c2f11...

**Comment by JoeWaddell** [comment]
So I have a quick partial fix. Changing from `==` to `<=` seems to do the trick in the `get_bw_change` method in heiferII.py, because it avoids setting a negative growth rate. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/107e361e-337e-4537-857b-05902fe9ab20)

However, this is just sloppy duct tape, because it doesn't solve the potential issue that animals are going over the gestation_length, and there are still complex values being introduced somewhere in the sim (now it's only warnings, but I still haven't yet tracked down where they're cropping up.).

First run with the prefresh_day at 60, second at 30, e.g. it still seems something is going quite wrong related to that value. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/bf5b2a3d-b28b-4e84-92f5-e404237c0664)

**Comment by JoeWaddell** [comment]
Closed by #1152
