### ISSUE TITLE
Division by zero error in crop module when testing pilot diets

### ISSUE THREAD

**Issue by harry-samuels** [RuminantFarmSystems/RuFaS#1088]
I have encountered an error when testing the input files for cohort 2 farm 14 and farm 15. When testing the file I receive the error message pasted below, indicating a "ZeroDivisionError"in 
File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/crop/crop_management.py", line 163, in cut_crop
    fraction_cut = self.data.cut_biomass / self.data.biomass
                   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~

## Expected Behavior
When running other completed sets of test files in the pilot testing branch, such as cohort 2 farm 13, the model runs without error and produces the simulation successful end message in the terminal.

## Current Behavior
When running both farm 14 and farm 15 I receive the following error message:

(base) Harrys-MacBook-Pro:MASM harrysamuels$ python3 main.py -v errors
RuFaS: Ruminant Farm Systems Model 2023
Simulating...
/Traceback (most recent call last):
  File "/Users/harrysamuels/Documents/GitHub/MASM/main.py", line 539, in <module>
    main()
  File "/Users/harrysamuels/Documents/GitHub/MASM/main.py", line 30, in main
    run_rufas(
  File "/Users/harrysamuels/Documents/GitHub/MASM/main.py", line 124, in run_rufas
    execute_simulations(
  File "/Users/harrysamuels/Documents/GitHub/MASM/main.py", line 407, in execute_simulations
    simulator.simulate()
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/simulation_engine.py", line 62, in simulate
    self._run_simulation_main_loop()
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/simulation_engine.py", line 77, in _run_simulation_main_loop
    self._annual_simulation()
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/simulation_engine.py", line 152, in _annual_simulation
    self._daily_simulation()
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/simulation_engine.py", line 85, in _daily_simulation
    self.state.field_manager.daily_update_routine(self.weather, self.time)
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/manager/field_manager.py", line 67, in daily_update_routine
    field.manage_field(time, current_conditions=current_conditions)
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/field/field.py", line 153, in manage_field
    self._check_crop_harvest_schedule(time, current_conditions)
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/field/field.py", line 636, in _check_crop_harvest_schedule
    self._harvest_crop(event.crop_reference, event.operation, time, current_conditions)
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/field/field.py", line 816, in _harvest_crop
    crop.crop_management.manage_harvest(harvest_operation_enum, self.field_data.name,
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/crop/crop_management.py", line 56, in manage_harvest
    self.cut_crop(collected_fraction=self.data.harvest_efficiency)
  File "/Users/harrysamuels/Documents/GitHub/MASM/RUFAS/routines/field/crop/crop_management.py", line 163, in cut_crop
    fraction_cut = self.data.cut_biomass / self.data.biomass
                   ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

## Possible Solution
I believe one of default the values for an input feed ingredient shared between these two diets potentially has an incorrect biomass of zero. I was unable to find the place from which these values are pulled and I am not super familiar with the crop module data structures so perhaps the solution would be more obvious so someone with more knowledge of the crop module.

## Steps to Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
1. Open the pilot_tesing_Dec2023 branch
2. Change the scenario_manager file to run the c2f14_metadata.json or c2f15_metadata.json file
3. Run the main.py file in terminal with verbose error output
4. Receive Error Message

**Comment by Isgotkowitz** [comment]
This issue is being caused because the configuration input file does not align with the weather input file. The default config file is being used, which specifies the simulation to start on day 244 of 2009 and end on day 264 of 2014. The weather input on the other hand contains data from day 1 of 2014 to day 365 of 2022.

There are two possible solutions to this issue:
1. Write a config file specific to pilot testing i.e. specifies the simulation to occur sometime between day 1 of 2014 and day 365 of 2022 (inclusive).
2. Unless the outputs produced by the Crop and Soil module are being utilized in the pilot farm analysis, delete all the crop and soil-related inputs from the pilot testing metadata files. Doing so makes the metadata simpler/easier to parse, makes simulations run faster, and does not add unused/unnecessary information to output files.

I recommend executing both 1 and 2. CC @harry-samuels @tomhuhh

**Comment by tomhuhh** [comment]
Thank you @Isgotkowitz! That clarifies things a lot! 

We will align the start and end dates between the configuration file and the weather file. 

I don't believe the outputs from the Soil and Crop Module is used for the current round of pilot testing. @jadamchick can correct me if I am wrong. Thus, I agree it would be safe for us to delete all the soil and crop related inputs from the metadata files and just use the default files instead? - this is more like a question for @Isgotkowitz 

Thank you everyone for your hard work!

**Comment by Isgotkowitz** [comment]
> Thus, I agree it would be safe for us to delete all the soil and crop related inputs from the metadata files and just use the default files instead? - this is more like a question for @Isgotkowitz

@tomhuhh I have not thoroughly checked, but it appears that the pilot farm metadata files are already using default Crop and Soil files, and I think those defaults should be deleted from the pilot farm metadata inputs.

This is possible because the Crop and Soil module handles input very differently from the Animal module. The Animal module always expects the Input Manager to contain some data that will define how it runs. The Crop and Soil module instead checks the Input Manager to see if it contains any input data with the `"field_properties"`. If there is some data with those properties, the Crop and Soil module will attempt to run, if not then the Crop and Soil module will not simulate anything.

**Comment by jadamchick** [comment]
Hi all - yes, I agree it makes sense to delete the crop + soil files from the metadata for the pilot testing (has been on my list of things to explore but haven't gotten there yet). I wasn't sure if we would need to hang onto some of those inputs because of how we are setting up the feed emissions factors (eg getting lat and long values from the field properties) -- but hopefully we will have FIPS code input for each pilot farm and won't need the lat/long (which does mean that each farm is going to need its own unique config file, just a heads up). 

Harry and Haowen, please feel free to go ahead and play around with this if you are running specific herds and I will do the same. If you need it to be applied to all of the farms at once for some reason, reach out to me and we can coordinate a plan for doing that!

**Comment by harry-samuels** [comment]
Hi All! Thank you so much Ed for the rapid response, after switching the problem files over to the pilot_testing_config files instead of the default_config file, I was able to run the files successfully. I also went through all of the current cohort 2 metadata files and changed any that were still using the default_config to use the pilot_testing_config instead, allowing them to run successfully as well.

I also tested out the removal of the crop and soil modules by taking out all sections referring to "field_properties", "crop_schedule_properties", "manure_schedule_properties", "fertilizer_schedule_properties", and "tillage_schedule_properties" from the metadata file for c2f13. The file was still able to run successfully and so I believe that it would be possible to make this change for all of the pilot farms if that was something we wanted to accomplish!

**Comment by Isgotkowitz** [comment]
@jadamchick @tomhuhh @harry-samuels can this issue be considered resolved?

**Comment by tomhuhh** [comment]
Hi @jadamchick! Based on the findings from @harry-samuels, I believe we can remove the crop + soil files in the pilot testing farm input metadata files without impacting the performance of the model. Should we wait until the feed emission factors are sorted out or should we proceed with this approach? Either way, I agree we can close this issue. Your insights are appreciated.

**Comment by jadamchick** [comment]
Hi all! Yes, I agree -- I think this issue can be considered resolved, and that we can remove those files/properties for the pilot testing farms. (I think that could be a good task for the fixathon list, I'll plan on adding it to the task list when we are able). Thanks everyone!
