### ISSUE TITLE
Update default animal input file 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1200]
As an initial step of establishing the benchmark for RuFaS outputs, I wanted to validate the animal input file by cross-referencing with literature data. During this process, I noticed some discrepancies between what is currently used in the default_animal.json file vs. what is suggested in the literature. I'm sharing it here for an open discussion to decide if and what we want to update.   

## Expected Behavior

For each animal input, there is a clear literature reference that recommends that value. 

## Current Behavior

There are some discrepancies as listed and highlighted in red here: https://docs.google.com/spreadsheets/d/10w20Bcf9JggyHwFZ-kXc2iBbJen-S6akzY2nUCdJtuE/edit?usp=sharing. 

The inputs highlighted in red are the values I propose to use as default inputs based on the literature that I found. 

## Steps to Reproduce

1.
2.
3.
4.

**Comment by tomhuhh** [comment]
Hello, I would like to draw your attention to this issue and any feedback/comments are welcomed. I hope to have something ready to be merged into main by the end of the day. Thanks! 

P.S. Joe and I noticed that there are two lactating pens currently in the default_animal.json file on main. We'll have to confirm with Aliister. After confirmation, we can decide if we would like to remove the additional lactating pen in this PR.

**Comment by tomhuhh** [comment]
Joe confirmed that we can remove the additional lactating cow pen.

**Comment by jadamchick** [comment]
Hi Haowen- Great idea/effort to pull together all of the references + data sources in one place. Two quick comments- 
- heifer estrus detection rate should be higher than 0.6. I know Li 2023 lists this as the value they used, but I don't see any reference to underlying data or other justification (though I could have missed it). After a quick search I'm not finding any academic literature on this, but maybe @krb78 has some ideas? 
- I thought we had created a set of heifer preg loss parameters in the heifer repro refactor? (realizing this isn't a direct question for you Haowen, just floating it out there). The loss rates we expect from lactating cows are much higher than what we would expect to see from pregnant heifers.

**Comment by krb78** [comment]
Hi team,

Yijing already made an issue (#1196) for the heifer pregnancy loss rates. She drafted a set of rates based on a heifer fetal survival curve that I found in a literature. “preg_check_day_1”: 32, “preg_loss_rate_1": 0, “preg_check_day_2”: 60, “preg_loss_rate_2": 0, “preg_check_day_3”: 200, “preg_loss_rate_3": 0.05.

So, I think cow estrus detection rate should stay at 0.6 but the heifer rate needs to be at 0.9 to be appropriate as a default. We could set some suggested ‘likely this will fall between 0.7 and 0.99’. We won’t find much about estrus detection rates in heifers because no one studies them 😆

Kaitlyn Briggs, DVM, MBA
C: 607.386.0040

If you receive an email from me outside of your own working hours, please do not feel pressure to respond outside of your own work schedule.
________________________________

**Comment by tomhuhh** [comment]
This has been addressed by PR #1294. Closing it...
