### ISSUE TITLE
Add units to all OM variables

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1253]
We want to add units to all output variables. To accomplish this task, you need to systematically search for calls to OutputManager's add_variable calls across the codebase and add units to info_maps. 

Question: How do we want to add units when a complex data type (dictionary for example) is passed?
@jadamchick @JoeWaddell @KFosterReed @krb78 @tomhuhh seeking your insight here. I can propose some technical solutions, but would like to know your perspective first.

Task List:
- [x] #1289
- [x] #1290
- [x] #1292
- [x] #1291

**Comment by JoeWaddell** [comment]
My instinct is that we should start with some examples: here's two that I work with regularly that pose different challenges.

A) Output key is `AnimalModuleReporter.report_ration_interval_data.ration_per_animal_for_pen_3_LAC_COW`
This is one where all items in the dict have the same units: kg. However, the number of keys in this dict can differ between pens (e.g. `...for_pen_2_CLOSE_UP` has a different number of keys, though all values are still in kg). 

B) Another output to consider: `AnimalModuleReporter.report_ration_interval_data.avg_rqmts_pen_3_LAC_COW` Here the dict has the same set of keys across pens/sims, but there are multiple units (some are in kg, some in g, etc.).

What I first imagined is that in addition to `info_maps` and `values`, we have `units`, which in the case of a dict would report a dict of the keys and their unit as a string. 

A second proposal is adding the unit as a suffix (if the user elects to, like using `info_maps`) to each key name in the output dict (and for the non-complex output names). This would presumably make CSV/JSON/report/graphing all easier, since those wouldn't need to be modified to get info from another field from om.

**Comment by ew3361zh** [comment]
Ed will break this up into 4 separate tasks based on the 3 main modules and 1 for miscellaneous variables. Allister will be assigned C&S and Manure, Niko will be assigned Animal and miscellaneous.

**Comment by krb78** [comment]
Can I be a dud and ask what a "dictionary" is?

**Comment by Isgotkowitz** [comment]
> Can I be a dud and ask what a "dictionary" is?

@krb78 A dictionary is a python data structure, and it is a collection of key-value pairs, for example:
```python
{
    "key_1": "value_1",
    2: "value_2",
}
```
they are very similar to the objects that you see in the JSON inputs, but Python dictionaries have significantly fewer restrictions.

Edit: [this](https://www.geeksforgeeks.org/python-dictionary/) has some good examples.

**Comment by krb78** [comment]
Ok, now that I understand a dictionary :) is there a way to pull units from the metadata for these? I'm just thinking that there are so many different keys and values. For example in the animal module, if we want how much of the diet a given ingredient makes up, we would need to call the key of feed id, the value of a # and then % as the unit... Or if we want the amount of synthetic fertilizer added the key would be N, the value would be a # and then kg would be the unit... 

I think I understand Joe's first idea best. But it sounds like his second idea would make the post-simulation analysis easier. I don't think I can weigh in on what it's like to implement either of these, but if the second idea makes post-simulation analysis easier, it's where I would lean toward. Sorry I'm not more helpful! 😕 🤷

**Comment by jadamchick** [comment]
Another consideration -- do we want to include any denominators ( __ per what) associated with the units? 
- eg if the unit is kg: kg/field, kg/animal, kg/pen 
- and/or time related, especially when something other than daily: kg/pen/interval, kg/cow/day, accumulated kg/simulation to date, etc.

**Comment by jadamchick** [comment]
> My instinct is that we should start with some examples: here's two that I work with regularly that pose different challenges.
> 
> A) Output key is `AnimalModuleReporter.report_ration_interval_data.ration_per_animal_for_pen_3_LAC_COW` This is one where all items in the dict have the same units: kg. However, the number of keys in this dict can differ between pens (e.g. `...for_pen_2_CLOSE_UP` has a different number of keys, though all values are still in kg).
> 
> B) Another output to consider: `AnimalModuleReporter.report_ration_interval_data.avg_rqmts_pen_3_LAC_COW` Here the dict has the same set of keys across pens/sims, but there are multiple units (some are in kg, some in g, etc.).
> 
> What I first imagined is that in addition to `info_maps` and `values`, we have `units`, which in the case of a dict would report a dict of the keys and their unit as a string.
> 
> A second proposal is adding the unit as a suffix (if the user elects to, like using `info_maps`) to each key name in the output dict (and for the non-complex output names). This would presumably make CSV/JSON/report/graphing all easier, since those wouldn't need to be modified to get info from another field from om.

For each of these two proposals, how would they differ when using report generator? I would give priority to a mechanism that would automatically include units somewhere in the column heading/label.

**Comment by JoeWaddell** [comment]
> Another consideration -- do we want to include any denominators ( __ per what) associated with the units?
>      * eg if the unit is kg: kg/field, kg/animal, kg/pen
>     * and/or time related, especially when something other than daily: kg/pen/interval, kg/cow/day, accumulated kg/simulation to date, etc.

Any solution should be sure to handle those complex units, though I know from a SWE standpoint there will need to be consideration of regex characters and how slashes are handled. @jadamchick Do you have examples of particularly complex units, e.g. using carats to denote exponents, as an example? 

> For each of these two proposals, how would they differ when using report generator? I would give priority to a mechanism that would automatically include units somewhere in the column heading/label.

The two ideas I proposed only really differ on the technical side of things, since in either case we'd have to map each variable within the complex data type to some unit. What I imagined is that the mapping would either be carried through as its own dictionary (first option, e.g. added to `info_maps`, or supplied as a separate field entirely), or used to modify the variable names at the time of adding them to the output manager (second option). 

I'm agreed with both of you that any solution to this should have the option to add units to the variable names in reports/CSVs/JSONs/graphs, with the default being to include units, since I can't think of many reasons not to include units (long names, redundant units, unitless, etc.). This (and how we want to supply the unit for each variable in a complex type) is probably the information @PooyaHekmati was looking for, since I imagine he has some good ideas on the SWE side of things.

**Comment by jadamchick** [comment]
> 
> Any solution should be sure to handle those complex units, though I know from a SWE standpoint there will need to be consideration of regex characters and how slashes are handled. @jadamchick Do you have examples of particularly complex units, e.g. using carats to denote exponents, as an example?
> 

I can't think of any outputs I use regularly that have exponents in them, but I'll keep my eyes out. Nothing else comes to mind as "complex" either..

**Comment by PooyaHekmati** [comment]
I'm rushing the answer here, I apologize if I'm being wrong. I don't think regex would be a concern, because we apply it on keys and variable names, not the units. We can append the units after regex matching so that we see them in the output as labels/captions.

**Comment by Isgotkowitz** [comment]
> Another consideration -- do we want to include any denominators ( __ per what) associated with the units?
> 
> * eg if the unit is kg: kg/field, kg/animal, kg/pen
> * and/or time related, especially when something other than daily: kg/pen/interval, kg/cow/day, accumulated kg/simulation to date, etc.

I think this is something that could be addressed with issue #1288. My proposal in that issue is to have one large enum with every single available option in it. @jadamchick this could be used to address you the consideration you mentioned, with something like the following:

```python
class RuFaSUnit(Enum):
    GRAMS = "g"
    KILOGRAMS = "kg"
    KILOGRAMS_PER_COW = "kg/cow"
    KILOGRAMS_PER_PEN = "kg/pen"
    KILOGRAMS_PER_PEN_PER_DAY = "kg/pen/day"
    KILGORAMS_PER_PEN_PER_YEAR = "kg/pen/year"
```

As new units come up, they can simply be tacked on to this Enum and used when recording variables.

**Comment by Isgotkowitz** [comment]
> What I first imagined is that in addition to info_maps and values, we have units, which in the case of a dict would report a dict of the keys and their unit as a string.

@JoeWaddell I like this solution as well. It would require some extra logic in the OM and postprocessing modules, but implementing it would not be too bad (famous last words).

Also I agree with @PooyaHekmati, using the solution of putting units in a "units" field in the info maps and automatically appending those units to variable names and keys would prevent Regex issues.

**Comment by allisterakun** [comment]
All sub-issues have been closed.
