### ISSUE TITLE
Volatile solids updates in the manure module 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1270]
The updates of the mass of volatile solids is important for us to track the mass balance. 

Currently in each of the manure treatment file, for example, `slurry_storage_outdoor.py`, only accumulated `total solids` is being updated when methane emission happens, while we should update accumulated `total volatile solids`, `degradable volatile solids`, and `nondegradable volatile solids` as well.  

When updating the accumulated `total solids` we should subtract four times of the methane emissions (Peterson et al. 2024: https://doi.org/10.1016/j.jenvman.2024.120233) to account for carbon loss from both methane and carbon dioxide. Alternatively, since we also calculate the carbon dioxide loss, we should subtract the total of methane and carbon dioxide from the accumulated `total solids`.  

Similarly, we should subtract mass losses due to methane and carbon dioxide emissions from the accumulated `total volatile solids`, `degradable volatile solids`, and `nondegradable volatile solids` as well. 

## Expected Behavior

We should subtract the correct amount of mass losses due to methane and carbon dioxide emissions from the accumulated `total solids`, `total volatile solids`, `degradable volatile solids`, and `nondegradable volatile solids`. 

## Current Behavior

Currently, only accumulated `total solids` is being updated when methane emission happens and the loss of carbon dioxide is not accounted for.  

## Possible Solution

Either subtract the total of methane and carbon dioxide emission or four times of the methane emissions as suggested by the literature. 

For updating the accumulated `degradable volatile solids`, and `nondegradable volatile solids`, we can first update the accumulated `total volatile solids` and use the ratio between `b1 `(1) an `b2` (0.01) to calculate the accumulated `degradable volatile solids`, and `nondegradable volatile solids`. `b1` and `b2` are constants used in the `methane_emission_from_slurry_storage` function in the `calculator.py` file. 

## Steps to Reproduce

1. In the `slurry_storage_outdoor.py` file, go to the `_daily_update_helper` function and look for `new_accumulated_liquid_manure_total_solids`.  
2.
3.
4.

**Comment by elle-andreen** [comment]
A couple comments and questions on this issue:

1. > Alternatively, since we also calculate the carbon dioxide loss, we should subtract the total of methane and carbon dioxide from the accumulated total solids.

I think this is only true for housing emissions, I don't think there exists a comprehensive method to predict storage CO2 emissions. My gut is that we should use the same ratio method to update VS and its degradable & non-degradable fractions anywhere that we are quantifying CH4/CO2 emissions.

2. I am seeing the Petersen et al. 2024 paper reporting a **molar** ratio of 1:3 for CH4 and CO2 emissions, which would be equal to 1:8.25 on a mass basis, but definitely want an SME to confirm that. So I think we would need to subtract CH4 emissions x 9.25, rather than x 4?

3. To start helping us clarify how the subtraction of VS should be done (using 'constant' in place of 4 or 9.25 or whatever number we decide on), this is my understanding of how we should be doing the subtraction. Feel free to comment anywhere that I may have something wrong here:

Updated TS = accumulated TS - daily CH4 emission * (constant)
Updated VS = accumulated VS - daily CH4 emission * (constant)
Updated VSd = accumulated VSd - daily CH4 emission * (constant) * b1 ratio (1 / 1.01 = 0.9901)
Updated VSnd = accumulated VSnd - daily CH4 emission * (constant) * b2 ratio (0.01 / 1.01 = 0.0099)

**Comment by elle-andreen** [comment]
Haowen and I created [this document](https://docs.google.com/document/d/1EfYQUIwoIrt05yWLauEefcdTlgkGkk0WX6EoVqrL6eQ/edit) that has additional detail on how/where these calculations should be modified. Please note as per the doc that issues 1269-1271 are interrelated and build upon one another. Let us know if there are further questions or clarifications needed!
