### ISSUE TITLE
Emptying manure pit 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1272]
Currently under some manure treatment methods, for example `anaerobic lagoon` ,manure pit is emptied at the end of every storage period, and we're not tracking the removed manure. We should instead apply these manure to the field for the soil and crop module. 

## Expected Behavior

The manure module keeps track of the mass in the manure pit. When soil and crop module calls for manure for field application, the manure gets transferred to the soil and crop module. Then the storage period clock gets reset. For example, if the storage period is 180 days, on day 150, the soil and crop module calls for manure, the manure module checks its storage and assign soil and crop module with manure, then instead of emptying on day 180, it will then schedule to empty on day 330 (150 +180). 

## Current Behavior

Some manure treatments do not empty the manure pit at all, which means manure mass keeps increasing in the pit. 

Some other treatments empty the manure pit, for example, `anaerobic lagoon`, but the removed manure just disappears and is not tracked. 

## Possible Solution

Add a function to move manure from the manure module to the soil and crop module for field application for all manure treatment methods. 

Implement the storage period emptying functionality for all manure treatment methods. 

Synchronize these two methods by checking the manure removal to soil and crop module first, and then adjust the emptying schedule.  

## Steps to Reproduce

1. Run a manure treatment scenario, and make sure your filter includes accumulated volatile solids 
2. Plot volatile solids against simulation day.  
3.
4.

**Comment by ew3361zh** [comment]
@tomhuhh a few questions for you:
1. Do you have a filter file set up that you're using for tracking this? Volatile solids show up a lot in the output files but I wasn't sure which was `accumulated_volatile_solids` - is it `total_volatile_solids` we're looking for? And is that tracked by pen?
2. Manure is transferred to C&S via ManureNutrientRequests which do subtract nitrogen, phosphorus, and dry_matter from ManureNutrients. We could potentially try to track volatile_solids along wih this group to ensure it's being subtracted at the same time a manure request is made by C&S. Or maybe that would be confusing since volatile solids aren't a "nutrient", what do you think?
3. Where should "the storage period clock gets reset" be happening? Is there currently a storage clock?
4. Where are volatile solids being removed in anaerobic lagoon? The only place I'm seeing them referenced is in the `_update_methane_emission()` method which sends them to GasEmissionCalculator to calculate methane emissions.

**Comment by tomhuhh** [comment]
Hi @ew3361zh! Thanks for looking into this! Great questions - 
1. I believe the `accumulated_volatile_solids ` is what we would like to update. It should drop when the `soil and crop` module calls for manure application or at the end of a storage period. Please see issue #1341 for more details on the filters and how to replicate it. 
2. Great to know that manure nutrients are already been tracked. I think it makes sense to me to track volatile solids along with this group. I would consider `volatile solids` as a `nutrient`. 
3. The reset should happen when the `soil and crop` module calls for manure to be used in field application (I'm uncertain where in the code that happens). I believe the current `storage clock` is the `storage time period`. 
4.  Correct. This is related to issues #1269 and #1270. The `volatile solids` should have been updated every time methane emissions happen. Currently the function `_adjust_accumulated_output` in the `anaerobic_lagoon.py` file resets the volatile solids but does not direct the volatile solids to the `soil and crop` module. 

Hope this helps. Please let me know if you have more questions!  

Thanks!
Haowen

**Comment by ew3361zh** [comment]
> 1. I believe the `accumulated_volatile_solids ` is what we would like to update. It should drop when the `soil and crop` module calls for manure application or at the end of a storage period. Please see issue [Storage manure not emptying at the end of each storage time period #1341](https://github.com/RuminantFarmSystems/MASM/issues/1341) for more details on the filters and how to replicate it.

Sorry, I think I'm still confused because of the naming and there are quite a lot of variables listed in the filter for #1341 - I'm not specifically seeing any variable named `accumulated_volatile_solids` - do you know if it's the `liquid_manure_total_volatile_solids` that's being added from the Accumulated_ManureTreatmentDailyOutput?

> 2. Great to know that manure nutrients are already been tracked. I think it makes sense to me to track volatile solids along with this group. I would consider `volatile solids` as a `nutrient`.

Sounds good.

> 3. The reset should happen when the `soil and crop` module calls for manure to be used in field application (I'm uncertain where in the code that happens). I believe the current `storage clock` is the `storage time period`.
> 4. Correct. This is related to issues [Volatile solids initialization in the manure module  #1269](https://github.com/RuminantFarmSystems/MASM/issues/1269) and [Volatile solids updates in the manure module  #1270](https://github.com/RuminantFarmSystems/MASM/issues/1270). The `volatile solids` should have been updated every time methane emissions happen. Currently the function `_adjust_accumulated_output` in the `anaerobic_lagoon.py` file resets the volatile solids but does not direct the volatile solids to the `soil and crop` module.

OK, to clarify:

1. Do we want the manure treatment to be fully emptied any time a manure request from C&S is made? The way it's set up now we have requests made based on nutrient (N or P mainly I believe) and the request only tries to get enough manure to fulfill that request and leaves the rest behind.
2. It sounds like we want the treatment emptied on a pre-set time period (the storage clock/storage time period). But when it's emptied, it should all go to C&S even if there is no manure request made? If not, where else should it go?
3. How should C&S handle manure that hasn't been requested?

**Comment by tomhuhh** [comment]
That is correct Niko! With the `accumulated volatile solids`, please look for variables similar to `Accumulated_ManureTreatmentDailyOutput_Pen_2_CLOSE_UP.liquid_manure_total_volatile_solids`. We want to make sure it works for all pens.

**Comment by tomhuhh** [comment]
> 1. Do we want the manure treatment to be fully emptied any time a manure request from C&S is made? The way it's set up now we have requests made based on nutrient (N or P mainly I believe) and the request only tries to get enough manure to fulfill that request and leaves the rest behind.

Basically there are two main routes that manure leaves the storage space. The first route is when the `soil and crop` module calls for nutrients. The amount of `volatile solids` to be removed is dependent on the amount requested by the `soil and crop` module. The other route is to empty the storage space at the end of the `storage time period`. The `storage time period` is an input that you can find in the config section of the `manure_management.py`. The ultimate goal is to reset the clock for `storage time period` every time manure is removed to the `soil and crop` module. This ultimate goal is described in the current issue. 

> 

> 2. It sounds like we want the treatment emptied on a pre-set time period (the storage clock/storage time period). But when it's emptied, it should all go to C&S even if there is no manure request made? If not, where else should it go?

That is a great question. In the case where the manure storage space (i.e. slurry storage pond, anaerobic lagoon, etc.) is emptied when there is not a call from the `soil and crop` module, it would be a great question for @KFosterReed. 

Ideally we would like to align the timeline of the requests from the `soil and crop module` with the timeline of `storage time period`.  

> 3. How should C&S handle manure that hasn't been requested?

I think this goes back to the discussion in question 2. This is not my area of expertise as of now. 

Hope it helps. Let me know if you have more questions. Thanks!

**Comment by ew3361zh** [comment]
Thanks, Haowen. I am going to mark the status for this as "blocked" for now until we can determine what we want to happen to the manure when the reception pit is emptied. I think it could be somewhat complicated if we're asking C&S to be able to handle that excess manure even without a manure request being made. I'm also not sure about the implications of aligning the manure applications in C&S with the schedule of the manure reception pit being emptied. Will bring @Isgotkowitz into this as well as a reference for the C&S side.

**Comment by KFosterReed** [comment]
I am sorry that I didn't read this issue more closely. We do not want to automatically apply the manure to the crop and soil at the end. We just want to report that there was extra manure that was not removed. @tomhuhh does that make sense?

**Comment by tomhuhh** [comment]
Thanks @KFosterReed! Thanks @ew3361zh! 

I agree with what has been said in terms of not automatically applying manure to the `soil and crop` module without a request from that module and keeping the remained manure in the storage space.  

However, I think if the `soil and crop` module does not call for manure as frequent (meaning demand of manure < supply of manure), the manure storage pond will eventually be filled up. At that point, we (maybe?) need to figure out what to do with the extra manure (i.e. empty the manure storage space when its full and record the manure mass) or maybe just assume an infinite manure storage space at the moment (?). I think this is my understanding of Niko's original question (#2) as well as my question for Kristan but also I am uncertain if she has an immediate answer for this. 

Niko, I believe this also answers your concerns about the alignment of the manure application schedule of the `soil and crop` module and the storage time period of the `manure` module. Ideally, from my understanding, we would like that the storage time period is the same as the duration between the calls for manure from the `soil and crop` module. 

Maybe to clarify it a little more, by `reset of the storage clock`, it means that for example, say the `storage time period` is 180 days, and on simulation day 100, the `soil and crop` module calls for manure, the manure storage space provides the manure if there is enough, and the `storage clock` gets reset and counts that day as the day 0 of the current `storage time period`. Thus, if there is no call from the `soil and crop` module in the next 180 days, the manure storage space will be emptied at day 280 (= 100+180).  

Sorry there are so many details related to this issue and I have been trying my best to include as many of them as possible. I apologize for any miscommunication in this process.  

In my opinion, it is an important (maybe not urgent) design and code structure issue because of its role in tracking nutrient flow (one of RuFaS's missions). Therefore, it definitely requires some manpower and attention to figure it out. As a next step, whoever is working on the requirement document for the `manure` module should definitely include this requirement in their document. Also, we probably should start a design doc to facilitate the resolving of this issue. 

Thanks! I'm happy to provide more information on my end including my understanding if it is still unclear.

**Comment by KFosterReed** [comment]
Adding a couple of thoughts in response to the conversation above: 

1. Right now, when there is a request for manure application via the manure field connector, the nutrients are removed from the ManureNutrients class but not from the manure storage objects (I am sure I am not using the right word here). The `accumulated_volatile_solids` variable mentioned above would be in the ManureTreatment objects. Similar thing for any other accumulated nutrient (nitrogen, mass, etc)
2. Haowen is correct that even when the manure field connector removes nutrients from the manure storages in addition to the ManureNutrient object, the total amount of manure removed might not be the total amount produced or put into the treatment/storage unit. Haowen's suggestion above to 'reset the storage emptying clock' is a great one but we still may end up with ever increasing manure and I think there is likely a better solution in the future. For this reason, I suggest that, for now, we always empty it on the storage emptying interval. This will not influence the availbility of manure for the crop and field module because the available manure is tracked through the ManureNutrients class. I think this will allow us to implement a simple solution for now and improve it in the future.

**Comment by KFosterReed** [comment]
Oh and one more comment about disappearing manure! Haha :)

When we do empty a manure storage/treatment unit, we just need to add outputs that indicate how much manure was emptied so we know the difference between what was applied and what was 'removed'.

**Comment by tomhuhh** [comment]
Wanted to make a note here to summarize the current status of the issue: 

The immediate solution is to record the amount of manure that is removed at the end of each storage time period and not worry about passing it on to the soil and crop module, as the availability of manure for soil and crop module is tracked by the ManureNutrients class and therefore is not affected by the emptying process.  

In this case, the next step is to implement the code to track the amount of manure removed for all manure storage treatments. This means we will need to make some modifications to the current `_adjust_accumulated_output` function.  

Thanks!

**Comment by ew3361zh** [comment]
Thanks @tomhuhh and @KFosterReed. I think I'm close to fully understanding what we want to happen for this specific issue but let me type it out and run it by both of you to make sure:

1. Ensure all manure treatment methods are emptying their respective manure reception pits according to the storage period clock.
2. When the reception pits are emptied, log the amount of manure being emptied at that time to Output Manager.
3. **(please confirm)** Don't adjust the ManureNutrients to track volatile solids because that may affect C&S manure requests.

Does that sound right? Am I missing anything?

**Comment by KFosterReed** [comment]
> Thanks @tomhuhh and @KFosterReed. I think I'm close to fully understanding what we want to happen for this specific issue but let me type it out and run it by both of you to make sure:
> 
> 1. Ensure all manure treatment methods are emptying their respective manure reception pits according to the storage period clock.
> 2. When the reception pits are emptied, log the amount of manure being emptied at that time to Output Manager.
> 3. **(please confirm)** Don't adjust the ManureNutrients to track volatile solids because that may affect C&S manure requests.
> 
> Does that sound right? Am I missing anything?

I think this is on the right track! Here are a couple of comments on 2 &3 above

2. My preference would be to avoid using the term 'reception pits' only because in the RuFaS manure management sequence, we have the Reception pit before the Manure treatments/storage methods and in this issue we are referring to the manure treatment methods. (Hopefully this doesn't add confusion!)
3. I think this is correct, to address this issue specifically, we do not want to adjust the ManureNutrients class. In general, the ManureNutrients class can and should track volatile solids (along with all other manure nutrients) but that is an issue for another day!

**Comment by ew3361zh** [comment]
Thanks, @KFosterReed. One additional question for you and @tomhuhh: 
As far as the manure treatment `storage_time_period`: it looks like there isn't one set for "open lots" and "anaerobic digestion" in the `manure_management.json` file. Do you have those available?

**Comment by tomhuhh** [comment]
Thanks Niko! Great observation and attention to details! I have some thoughts regarding your questions but would like to bring @elle-andreen into this conversation as well. Thanks!

**Comment by elle-andreen** [comment]
> Thanks, @KFosterReed. One additional question for you and @tomhuhh: As far as the manure treatment `storage_time_period`: it looks like there isn't one set for "open lots" and "anaerobic digestion" in the `manure_management.json` file. Do you have those available?

Yes, for the Open Lots treatment, I think `storage_time_period` should be user-inputted if possible, similar to the other manure treatments. I see in the metadata properties that we have a default of 120 days for `storage_time_period`, but then the `manure_treatment_configs.py` file contains different values for most manure treatments (e.g., 365 days), with nothing for open lots (or CBPB or composting). Either way, I'm not exactly sure what a suitable default value for this would be. [A precursory google search says 1 year](https://ww2.arb.ca.gov/sites/default/files/classic/fuels/lcfs/fuelpathways/comments/tier2/b0105_report.pdf)? @krb78 may have a better sense of it, or we could ask the SME contact for Open Lots.

For anaerobic digestion, I think there should be no storage time variable (or storage time should = 0, if need be) for RuFaS purposes. `Hydraulic retention time` as it's used currently in RuFaS is a factor in determining CH4 production in the digester using the Chen equation, although in the real world, HRT does relate to how long manure would stay in the digester. However, the digester represented by RuFaS right now is a continuous flow system, so I'm pretty sure we're making the assumption that manure will flow into and out of the digester on the same day. So even though it's a bit of a deviation from reality, I don't think we need to include any storage time for anaerobic digestion.

**Comment by krb78** [comment]
Hi! I think it's a little strange to have a "storage time period" for an open lot because I think harrowing usually involves just moving the manure around and we never really go in and scrape all the manure out to "start over"... but I think a 365 day default will be fine because at least for the time being, most of our scenarios are being run for years and just the last year of data is being used to generate reports. The CBPB time period default would be appropriate to be ~4 months, and the compost default would be appropriate to be 1 year as well.

**Comment by krb78** [comment]
Elle, I think your synopsis of the "storage time period" for the digester is also correct. It is not 1 year, but once it is at capacity, manure flows out daily, rather than being emptied every 2 weeks (for example)

**Comment by ew3361zh** [comment]
Thank you @krb78 and @elle-andreen! This is really helpful context. Maybe @KFosterReed can weigh in to get final consensus here but I think we have the following guidelines going forward for `storage_time_periods`:
`slurry storage underfloor`: 120 days
`slurry storage outdoor`: 120 days
`anaerobic lagoon`: 365 days
`anaerobic digestion`:  n/a (essentially we won't ever empty it in the same way we're emptying the other treatments)
`cbpb`: 120 days (is currently 365 days in `manure_management.json`)
`open lots`: 365 days
`composting`: 365 days

Does that look right? Thanks everybody!

**Comment by KFosterReed** [comment]
This sounds great to me!
