### ISSUE TITLE
Investigate failing Readme Update Github Action

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1374]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [X] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

Currently we are seeing the Commit and Push test coverage to Readme update action in Github failing in multiple PRs (#1373, #1361, #1263 e.g.).

From PR 1373:
![Screenshot 2024-03-06 at 10 53 13 AM](https://github.com/RuminantFarmSystems/MASM/assets/70217952/1efd507d-b20b-43d3-b0ea-b8c587986213)
From one of Joe's PRs:
![image (5)](https://github.com/RuminantFarmSystems/MASM/assets/70217952/42cac908-79db-402a-beb7-4520f4d95578)

## Intention

When the testing action on Github runs, it should automatically update the Readme with the current % level of testing coverage. With this action failing, the testing coverage % is no longer kept up to date.

## Request

Investigate why this is happening and what the root cause is. 
There is another recent action, the MyPy error count, that commits and pushes changes to the Readme. That action seems to be successful currently. 

It's worth seeing if this second commit and push to the Readme is affecting the testing update action. 

Or perhaps there is something the MyPy Readme update action is doing that could be added to the testing Readme update action to make it work again consistently.

**Comment by ltp23** [comment]
After some digging, this issue seems to resolve by itself after combining both pytest and mypy actions into one workflow (PR #1448). The cause of this issue, in my opinion, was that before that PR, we'd had two separate commits trying to write to the same README file and without pulling in the changes from the first commit, it'd led to merge conflicts during the second commit. The simple solution here is to only update the README file once and then make one commit.

Although this was more of a investigative issue, a follow-up task that could be done is to combine the two update badge scripts into one. I have created a separate branch for it (`combine-badge-scripts`). This can be revisited after the work related to the Black formatting action is complete (Issue #1517).
