### ISSUE TITLE
Remove calls to FCC's API for getting county code from the PurchasedFeedEmissionEstimator class

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1391]
In the `PurchasedFeedEmissionEstimator` class, there is an API call in the `_get_county_code()` method. We want the Input Manager to handle this part so we can maintain input source agnosticism.

- Expand metadata options to include API requests. We specify API endpoints and other things like data type, and constraints.
- Write one or more methods in the Input Manager class to enable this feature.

--- 

Edit 1: 

- Reconsider whether the `PurchasedFeedEmissionEstimator` class needs to make an API call at all.

Edit 2:
- Instead of building in an API call for getting the county code, the only way that RuFaS gets the county code should be through the config input file.
- Querying the FCC's API should be done through one of the existing services for getting RuFaS input (weather scraper, soil profile builder, etc).

**Comment by Isgotkowitz** [comment]
Adding API calls to the metadata would definitely be a useful feature that would enable much better integrations with other services out there.

My two cents is that the FCC's FIPS county code API is not the best candidate for adding an API call for. The API call that is in there now is hardly ever used because the county code is provided in the Config input file. And the FIPS code can be collected very easily by a user, so it seems reasonable to leave the burden of collecting it on the user instead of shifting it to a third-party API with questionable reliability.

I think better use cases for the API calls in the metadata would be the weather input generator and the soil profile builder, but those would both need some work done to them before they could be deployed as running services.
