### ISSUE TITLE
[Herd Generation] Herd generation fails when number of simulated days and initial animal count are below certain threshold

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#1395]
If the number of days that a herd is simulated for is low enough, the Herd Factory will crash

## Expected Behavior

RuFaS should be given any valid combination of initial animals in a herd and number of days to simulate and generate a replacement herd based on those inputs.

## Current Behavior

When the initial number of animals and days to simulate them for are low enough, the Herd Factory crashes.

## Steps to Reproduce

1. Navigate to the `main` branch
2. Set `"initial_animal_num"` to 100 and `"simulation days"` to 4865 in the `"herd_initialization"` object in `default_animal.json`.
3. Run the default scenario with the flags `-I -s -t -v errors`
4. Observe results. There should be an error produced that is similar to:

![herd_generation_error](https://github.com/RuminantFarmSystems/MASM/assets/43901812/235e326d-569b-4e8c-b405-1836a596cfa1)

**Comment by allisterakun** [comment]
Grooming session:
Figure out how the exact threshold value that will crash the simulation can be calculated. From there, this issue can be fixed once cross-validation is implemented in the InputManager.

**Comment by ew3361zh** [comment]
The two main threshold numbers I tested were:
- `initial_animal_num` (default 10,000)
- `simulation_days` (default 5,000)

both of which are in the `default_animal.json` input file.

Keeping `simulation_days` at the default of 5,000:
- herd initialization fails at `initial_animal_num` <= 114
- herd initialization passes at `initial_animal_num` > 114
- These `initial_animal_num`s create successful herd initializations for 3,391 <= `simulation_days` < 5,000

Keeping `initialial_animal_num` at the default of 10,000:
- herd initialization fails if `simulation_days` < 3,000 (because that's the threshold set in `HerdFactory` in the `_heiferIIIs_update()` method for `replacement_cow` generation.
- Below that 3,000 threshold, the `initialize_herd()` method will fail at this line:

`self.post_animal_population = self._random_sample_with_replacement()`

Because that function tries to get the numbers of each of these types of animals sequentially:

```
post_calves: List[Calf] = self._random_sample_with_replacement_by_type("calf")
        post_heiferIs: List[HeiferI] = self._random_sample_with_replacement_by_type("heiferI")
        post_heiferIIs: List[HeiferII] = self._random_sample_with_replacement_by_type("heiferII")
        post_heiferIIIs: List[HeiferIII] = self._random_sample_with_replacement_by_type("heiferIII")
        post_cows: List[Cow] = self._random_sample_with_replacement_by_type("cow")
        post_replacement: List[Cow] = self._random_sample_with_replacement_by_type("replacement")

```

And the replacement cows have the highest threshold of days (3,000) to start being created.
Cows are generated starting on day 660 (threshold when `days_in_preg` == `gestation_length`).
Heiferiiis are generated starting on day 398.
Heiferiis are generated starting on day 380 (relates to the value for `breeding_start_day_h` in the `default_animal.json` file).

I'm not sure which of these numbers/processes will be updated with Animal refresh so it needs to be kept in mind this is just documentation of these thresholds as things stand as of the writing of this comment.

**Comment by ew3361zh** [comment]
@allisterakun @Isgotkowitz could you please review and leave a comment of whether I can close this issue or if you'd like to see some additional data?

Thank you!

**Comment by Isgotkowitz** [comment]
@ew3361zh I would be curious to know if the herd size specified in the animal input file matters as well. I think this number is important because the problem basically comes down to not having enough cows to construct the herd at the beginning of the simulation, and this can happen because the number of cows supplied in the herd is too low, or because the number of cows called for in the simulation is too high.

I am curious to hear @allisterakun 's thoughts, I think he mentioned that the number of cows in the initial herd should not matter when a new herd is constructed because cows can be reused when constructing the initial herd. If this is the case then that will be the solution to this problem, and this issue could be replaced with a new one to implement the behavior that should be happening.

**Comment by ew3361zh** [comment]
When running a `HERD_INITIALIZATION` task with the `herd_num` up to 10000, there was no effect on the success of the task.
I also tried it with upping the `calf_num`, `heiferI_num`, and `replace_num` by factors of 100-1000 and the task was successful.
When I upped ALL these numbers at once, the process of herd initialization was successful but the processing afterward was taking a while and I stopped it before completion. But the bar of generating a herd reached 100%.

**Comment by Isgotkowitz** [comment]
@ew3361zh I think the investigation of this issue is pretty much wrapped up. If you have any suggestions on what an appropriate fix would be, this would be a good place to leave them. Also writing up an issue for actually fixing herd initialization would be good too (if this hasn't happened already) and then I think this issue is good to be closed out.

**Comment by allisterakun** [comment]
This is a great analysis! Very sorry about the delay in review. 

> I am curious to hear @allisterakun 's thoughts, I think he mentioned that the number of cows in the initial herd should not matter when a new herd is constructed because cows can be reused when constructing the initial herd. If this is the case then that will be the solution to this problem, and this issue could be replaced with a new one to implement the behavior that should be happening.
It turns out that a minimum threshold exists for the `initial_animal_number`. It makes sense that if we start with a small number of animals and only have certain days of simulation, we may not have any cows (or animals at any other stages) to choose from at the end. For example, here are snapshots of the animal population at the end of the simulation for different `simulation_day` and `initial animal_num` combinations:
- `simulation_day = 5000; initial_animal_num = 114`:

> calves: 6
heiferI: 13
heiferII: 9
heiferIII: 0
cow: 22
replacement: 62

As we can see, herd generation fails because we don't have any heiferIIIs.
- `simulation_day = 5000; initial_animal_num = 115`:

> calves: 2
heiferI: 6
heiferII: 8
heiferIII: 3
cow: 24
replacement: 66

Keeping the `simulation_day = 5000`, if we increase the `initiail_animal_num` by 1, we would have at least some animals at all life stages to draw from at the end of the simulation.

- `simulation_day = 100000; initial_animal_num = 114`:

> calves: 0
heiferI: 0
heiferII: 0
heiferIII: 0
cow: 0
replacement: 499

I thought maybe increasing the `simulation_day` would compensate for the small `initial_animal_num`, but I think we also have an upper limit because if we run the simulation for too long, all the animals end up being replacements.

- `simulation_day = 7000; initial_animal_num = 114`:

> calves: 5
heiferI: 11
heiferII: 14
heiferIII: 1
cow: 36
replacement: 130

Following the thought that increasing the `simulation_day` could maybe compensate for the small `initial_animal_num`, I increased the `simulation_day` to 7000, which seems to be working. 

- `simulation_day = 7440; initial_animal_num = 114`:

> calves: 1
heiferI: 19
heiferII: 15
heiferIII: 2
cow: 34
replacement: 150

- `simulation_day = 7441; initial_animal_num = 114`:

> calves: 0
heiferI: 20
heiferII: 15
heiferIII: 2
cow: 34
replacement: 150

I was looking for the upper bound of `simulation_day` when `initial_animal_num` is set to 114, and I found that 7440 is the limit. 

- `simulation_day = 8500; initial_animal_num = 114`:

> calves: 3
heiferI: 13
heiferII: 12
heiferIII: 1
cow: 25
replacement: 195

However, it seems that when fixing the `initial_animal_num` at 144, the min and max limitation on `simulation_day` is not absolute. We thought 7440 was the limit in the previous step, but if we set the `simulation_day` to 8500, we have enough animals to draw from again.

So, I think my conclusion is that it's hard to set an absolute minimum and maximum for these two parameters (`simulation_day` and `initial_animal_num`) because it is impossible to predict the herd structure at the end of the simulation. From observation, I think the limiting factors are the number of **calves** and **heiferIIIs** at the end of the simulation. In conclusion, I think at the end of the day, even if we start with a large enough `initial_animal_num`, it is still up to luck to decide if we'd have at least one animal at each life stage to pick from at the end of the simulation.



> And the replacement cows have the highest threshold of days (3,000) to start being created.
> Cows are generated starting on day 660 (threshold when `days_in_preg` == `gestation_length`).
> Heiferiiis are generated starting on day 398.
> Heiferiis are generated starting on day 380 (relates to the value for `breeding_start_day_h` in the `default_animal.json` file).

These are great insights; thanks, Niko!



> I'm not sure which of these numbers/processes will be updated with Animal refresh so it needs to be kept in mind this is just documentation of these thresholds as things stand as of the writing of this comment.

I don't believe that these would change for the animal refresh.

Overall, great job, Niko! Approving this issues!
