### ISSUE TITLE
Generating only desired output files 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1397]
**Is your feature request related to a problem? Please describe.**
Is it possible to filter out the other output files and only generate the desired output file(s) as highlighted below?  

<img width="915" alt="Screenshot 2024-03-07 at 11 20 56 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/52800053/77d49bb9-af08-4fc5-bde0-b488a3a62e34">

This feature can also benefit the users when sometimes the user forgets that they have multiple filters (with undesired ones) to avoid generating output files for all the filters.  

This can save runtime too because some of these output files take a long time to generate. 

To conclude, it may be beneficial to include all these output files for development purposes, but it seems impractical in real world application.   

**Describe the solution you'd like**
When initializing the simulation, there is an option to select which output files the user would like to generate. 

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by Isgotkowitz** [comment]
@tomhuhh I am working on this issue. I think we need to keep the overhead files (errors, logs, warnings, var names, etc.) because they help provide important context, and it is good to always have them generated even when you think you're not going to need them.

Would an acceptable fix to this issue be to put the different types of outputs of into different folders? I.e. reports go into a report folder, jsons go into a jsons folder, and logs/error/warnings go into their own folder.

**Comment by Isgotkowitz** [comment]
Moving this issue to blocked until the task manager is finished.

**Comment by Isgotkowitz** [comment]
Now that task manager is finished, options can be added to tasks for what the different output directories should be for JSONs, reports, and simulation messages.

**Comment by tomhuhh** [comment]
Thanks for following up on this, Ed! I have a small concern about the space the simulation outcomes might take up on my computer, given the multiple rounds and the files they generate. Perhaps we could offer users the option to select which files they'd like to output for each simulation scenario? I think that might help manage the storage better. Thanks!

**Comment by Isgotkowitz** [comment]
> Thanks for following up on this, Ed! I have a small concern about the space the simulation outcomes might take up on my computer, given the multiple rounds and the files they generate. Perhaps we could offer users the option to select which files they'd like to output for each simulation scenario? I think that might help manage the storage better. Thanks!

When you say "select which files they'd like to output for each simulation scenario" do you mean which filters they would like to have files produced for?

**Comment by tomhuhh** [comment]
Yes, that could be the filters the users prefer or the output information they prefer. In the second case, an example could be they would like to exclude the variable name and warning output files. Also, I think in general this feature is at a lower priority. Thus, I would not worry too much about it if you have other higher priority tasks. Thank you again for looking into this!

**Comment by Isgotkowitz** [comment]
> Yes, that could be the filters the users prefer or the output information they prefer.

This option exists in the TaskManager - by specifying the "filters_directory" for different tasks, users can have different simulations/tasks generate different sets of outputs.

> In the second case, an example could be they would like to exclude the variable name and warning output files. Also, I think in general this feature is at a lower priority. Thus, I would not worry too much about it if you have other higher priority tasks. Thank you again for looking into this!

Echoing my comment from above, it may not be a good idea to not produce overhead files like the variable names and warnings files every time - but I will check with @PooyaHekmati about this. Fortunately though, a lot of strides have been made since this issue was written. The get data logs output file is now orders of magnitude smaller, so hopefully the size of output files are not too big of a concern anymore.

**Comment by PooyaHekmati** [comment]
> 
> Echoing my comment from above, it may not be a good idea to not produce overhead files like the variable names and warnings files every time - but I will check with @PooyaHekmati about this. Fortunately though, a lot of strides have been made since this issue was written. The get data logs output file is now orders of magnitude smaller, so hopefully the size of output files are not too big of a concern anymore.

Maybe add a new input to task manager properties which silents/mutes the log files (both IM and OM)? The default should be false, meaning we generate these files unless explicitly asked by user to no generate them.
