### ISSUE TITLE
Manure not emptied properly when storage period is one day 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1403]
The manure pit is not emptied correctly with the current methodology of emptying the pit at the end of each storage time period according.  

## Expected Behavior

When the storage time period is set to 1, it should empty on a daily basis. 

## Current Behavior

When the storage time period is set to 30 days. It is updated correctly. 

![Storage period 30 days](https://github.com/RuminantFarmSystems/MASM/assets/52800053/0dc93939-eead-46b4-8307-814c39fcce95)

When the storage time period is set to 1 day. It does not work. 

![Storage period 1 day](https://github.com/RuminantFarmSystems/MASM/assets/52800053/0e6dbcac-3f31-45e9-8e46-5672bcdf6b2c)

## Steps to Reproduce

1. Set `storage_time_period` as `1` for the manure treatment you select. 
2.
3.
4.

**Comment by ew3361zh** [comment]
This issue does seem to still be relevant - it's specific to the `storage_time_period` being set to 1 day.
I took a look at the code and in base_manure_treatment.py the `_adjust_accumulated_output()` method has the check on when to empty set to if `self._sim_day % self.storage_time_period == 1:` which I think is causing the issue with it not emptying when the storage period is set to 1 day (so setting it `== 0` would seemingly fix that).

I tried implementing this but didn't get the result I expected so I think this needs a little more attention (still should be a relatively easy and short fix):

<img width="1333" alt="Screenshot 2024-07-25 at 5 23 44 PM" src="https://github.com/user-attachments/assets/4ae1fad1-b183-4443-8c67-862ba5600ded">

Update - after thinking it through, this graph actually makes sense given the manure treatment is emptied every day. There wouldn't be the same pattern as for the 30 day emptying period because it's not accumulating at all. There's a much smaller range for the daily output.
