### ISSUE TITLE
Can no longer "choose own adventure" for manure separator 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1425]
## Expected Behavior
Be able to name and define the specs for a variety of manure separator systems beyond just the two listed (rotary screen and screw press). 

## Current Behavior
Because there are only 2 patterns listed in the metadata properties for manure_separator, it will not accept anything named other than these two. 

## Possible Solution

I wonder if the solution for manure handlers in PR #1250 would work here, allowing different names/variations of separator. You might still have to specify "type" as one of the two listed, but at least could name it according to its true identity (and update the specs accordingly). 

## Steps to Reproduce

1. In manure_management.json, copy/paste one of the manure_separator blobs, rename the type to "weeping wall", and specify manure_separator in one of the manure management scenarios as "weeping wall"
2.
3.
4.

## Context (Environment)

Many pilot farms have inputs for manure separators that are different from the two listed -- either because they represent another separator type entirely, or a combination of multiple separators used together.  These farms will not run without changing the separator inputs. 

For now, you can work-around by just altering the specs of one of the listed separators while keeping the name "screw press" or "rotary screen", but seems confusing/error-prone when what is really meant is "weeping wall" or another separator type or combination. 

There is no way to indicate in the .json that "where this says screw press, I really mean weeping wall."

**Comment by Isgotkowitz** [comment]
@jadamchick this is mentioned in #1118. It is folded into #1237, but if this is a high priority issue then we can update the issue to reflect this.

**Comment by jadamchick** [comment]
Thanks @Isgotkowitz. I think it's more annoying than urgent for now, but should be addressed soon. It is probably fine to include in the more comprehensive updates. Tagging @krb78 here so she is aware and can weigh in if needed.

**Comment by krb78** [comment]
Not URGENT, but something that FARM ES expects to be possible, so it definitely needs to be on the "fix in 2-3 months" list. From what I understand here, it seems we can update the configs, just not the name, which is just annoying and probably more error prone than being able to have 6 additional manure separator configs with separate names to represent the total we need to use in FARM ES.

**Comment by elle-andreen** [comment]
I agree that making the separator name configurable is a good first step to avoid confusion. For mechanical-type separators like screw presses or drums (or belt presses, centrifuges, etc. that are mechanical/short term), the workaround Julie gave is acceptable, because mechanical separators all would work in RuFaS more or less the same way - they just separate nutrients from the manure based on the user-defined separation values. The other consideration though is that each existing separator type also has their set of defaults and min/max values in the metadata properties, and your desired separator values may fall outside these. There has been discussion of implementing a 'custom' separator option that will accept any numerical value for separation efficiencies, to represent a multi-unit/complicated/otherwise not well-represented separator. I think that would be pretty easy to implement and would circumvent this problem for now.

It gets a little more complicated (as I'm sure you guys have thought about already) if you're trying to represent something like a weeping wall or settling basin, where 1. manure may be retained in the separation apparatus for a lot longer than a mechanical separator, and 2. methane and other emissions may result during this time. We can approximate the nutrient separation from these types of systems using a 'custom separator' option, but we will have to eventually account for the other aspects of these types of separators that we're able to reasonably ignore for more mechanical-type separators.

**Comment by Isgotkowitz** [comment]
Issue #1524 has been written to address this issue.
