### ISSUE TITLE
[AnimalModule] Animal Module Uncalled Functions

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#1466]
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [x] Medium: the issue affects functionality but has a workaround
- [ ] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Description
Please refer to this Google Sheet: [Uncalled Functions in RuFaS](https://docs.google.com/spreadsheets/d/1l3SucZs4BqUZsFk7SPg_A9ksz8cjXR8cWicGUuWp7uA/edit#gid=0). For the following uncalled functions in the animal module, please reach out to the SMEs or SWE that are familiar with the function to determine if they should be kept or removed:
1. `AnimalManager.get_initial_herd_summary()`
2. `Pen.current_pen_ration()`
3. `AnimalManager._create_default_pen()`
4. `AnimalManager.avg_pen_dist()`
5. `AnimalManager.daily_update_id_map()`
    1. `AnimalManager.track_former_pen_population()` (only occurrence is in `AnimalManager.daily_update_id_map()`)
    2. `AnimalManager.remove_animals_from_herd()` (only occurrence is in `AnimalManager.daily_update_id_map()`)
    3. `Pen.set_up_new_animal()` (only occurrence is in `AnimalManager.daily_update_id_map()`)
    4. `AnimalManager.calculate_pen_rations()` (only occurrence is in `AnimalManager.daily_update_id_map()`)
6. `AnimalModuleReporter.report_pen_manure()`
7. `Cow.get_general_estrus_detection_rate()`

Please remove the function if necessary and update the Google Sheet.

**Comment by ew3361zh** [comment]
@JoeWaddell this is the list of potentially stale (uncalled) functions within the Animal module. Maybe we can discuss this later this afternoon if you have some time.

**Comment by ew3361zh** [comment]
AnimalManager.get_initial_herd_summary() - Allister - in herd generation - related to #1463 
- discussed with @allisterakun and it can be removed - no plans to be implemented and not needed currently. Not related to #1463 after all.

Pen.current_pen_ration() - Loi and Joe - just accessing attribute of ration for Pen.
- discussed with @ltp23 - not implemented and no plans to implement. Will remove.

AnimalManager._create_default_pen() - Joe - he will talk to Kristan. Possibly get rid of because of duplicate pen fun he wrote.
AnimalManager.avg_pen_dist() - seems important, okay to keep, talk with Animal action items dev. Has to do with Animal activity.

AnimalManager.daily_update_id_map() - 
AnimalManager.track_former_pen_population() (only occurrence is in AnimalManager.daily_update_id_map())
AnimalManager.remove_animals_from_herd() (only occurrence is in AnimalManager.daily_update_id_map())
Pen.set_up_new_animal() (only occurrence is in AnimalManager.daily_update_id_map())
AnimalManager.calculate_pen_rations() (only occurrence is in AnimalManager.daily_update_id_map())

id_map() funs are likely all being depricated but Joe and Loi would be the ones to consult on.

- discussed with @ltp23 and his initial thought is that all of these can be removed because there is a replacement being used instead.

AnimalModuleReporter.report_pen_manure() - Loi - manure output is sent to OM more atomically in other ways.
- discussed with @ltp23 - look into whether `report_pen_manure_properties()` method. Loi wasn't familiar with it. Said we could look into both and then likely pick 1. Ask about hard-coded `reference_variable` in `report_pen_manure_properties()`. This function was likely created by Joe.


Cow.get_general_estrus_detection_rate() - Loi - repro refactor - Joe can look at design doc to see if this has a reference for a future method.

- discussed with @ltp23 and he thinks it is being used. It is overridden in HeiferII so may be escaping detection of use by scanner.

**Comment by ew3361zh** [comment]
### **Update**
**Keep:**
- Cow.get_general_estrus_detection_rate() (Loi, Joe)
- AnimalManager.avg_pen_dist() (Joe)

**Remove:**
- AnimalManager.get_initial_herd_summary() (Joe, Allister)
- Pen.current_pen_ration() (Loi, Joe)
- AnimalManager.daily_update_id_map() (Loi, Joe)
- AnimalManager.track_former_pen_population() (Loi, Joe)
- AnimalManager.remove_animals_from_herd() (Loi, Joe)
- Pen.set_up_new_animal()  (Loi, Joe)
- AnimalManager.calculate_pen_rations() (Loi, Joe)
- AnimalModuleReporter.report_pen_manure() (Loi, Joe)
- AnimalManager._create_default_pen() (Loi, Joe, Kristan)
