### ISSUE TITLE
Need for clarity on how animals entering the herd get their attributes 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#1501]
It isn't clear how new animals in a herd are acquiring attributes -- from the animal.json input file and/or from the animal_population.json herd. This applies to animal entering the herd through 2 paths: 
a) born as calves
b) purchased as heiferIII's (replacements)

Specific questions to answer: 
a) When calves are born from cows who originated from the animal_population.json, do they acquire attributes from their mother or from the input animal.json? 
b) When replacements (heiferIII's) are purchased, are any of their attributes updated to match the herd inputs? (maybe repro protocols?)

## Expected Behavior

Maybe naively, I expect the values I fill out in the animal.json to be reflected in the animals in my herd. 
More importantly, if the above is not true for 100% of attributes for 100% of animals, I expect there to be some guidance/reference about which values come from which sources for which animals.  This will inform a) how strongly to expect the herd outputs to be influenced by the inputs vs. the underlying generated population, and b) how to decide when it is important to generate a herd-specific animal population vs. to use the default. 

## Current Behavior

I'm not sure. I know the breed of replacements is not updated, as evidenced by this result. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/ccb3c2a7-8114-4d9e-8520-c38ebfe585bf)

I think I have heard chatter about some repro protocols being updated when an animal enters the herd from the animal_population. The rest of my knowledge is just assumptions. 

## Possible Solution

Some sort of documentation that systematically identifies which attributes (things specified in the animal.json) of an animal are defined by the input.json vs. by the animal_population.json, for animals who enter the herd through a) born as calves and b) purchased as heiferIII's. 

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

This is important for: 
a) knowing what outputs to expect based on the inputs entered (in other words -- how much do I expect my outputs to be influenced by what I put in the animal.json inputs vs. by the inputs that were used to create the animal_population.json)
b) deciding when it is important to generate a customized herd-specific animal_population vs. to use the default population/s.

**Comment by jadamchick** [comment]
Possibly related question: are replacement animals cows or heiferIII's?  in `lifecycle.py`, it looks as though the replacement_market is a list of cows. but when they enter, the output incremented is "bought_heifer_num". I suspect there is more to it than what I'm seeing here, because I get the impression that they enter as heiferIII's.. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/49da37e9-40a2-4260-b73c-caf97cd6db33)

![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/a00cdb70-c7e7-4a09-951f-0628ea4059eb)

**Comment by ltp23** [comment]
### Newborn calves generated during the standalone herd initialization (`herd_factory.py`)

In the `herd_factory.py` file, the method `_cow_update()` handles the creation of new calves:

```
def _cows_update(self) -> None:
    # ... (omitted)
    for cow in self.pre_animal_population.cows:
        # ... (omitted)
        if new_born:
            args = AnimalBaseInitArgsTypedDict(
                id=self.pre_animal_population.next_id(),
                breed=self.breed,
                birth_date=0,
                days_born=0,
                p_init=cow.p_gest_for_calf,
                birth_weight=cow.calf_birth_weight,
            )
            cow.p_animal = cow.p_animal - cow.p_gest_for_calf + cow.p_growth + cow.dP_reserves
            cow.p_gest_for_calf = 0
            cow.calf_birth_weight = 0
            calf = Calf(args)
            if not (calf.culled or calf.sold):
                self.pre_animal_population.calves.append(calf)
```

When a new calf is born during the standalone herd initialization:

- The calf's breed is set to `self.breed`, which is derived from the `animal.json` input file (`im.get_data("animal.herd_information.breed")`).
- The calf's initial phosphorus value (`p_init`) is acquired from the mother cow's `p_gest_for_calf` attribute.
- The calf's birth weight is acquired from the mother cow's `calf_birth_weight` attribute.
- Other attributes like `birth_date` and `days_born` are set to default values (0). This leads to a curious behavior I'm only aware of recently in which `days_born` and `days_in_preg` are the same.

So overall, newborn calves acquire some attributes from their mother (e.g., initial phosphorus value and birth weight) and some attributes from the animal.json input file (e.g., breed).

### Newborn calves generated during the normal simulation (`life_cycle_manager.py`)

In the life_cycle_manager.py file, the method `_handle_new_born()` handles the creation of new calves during the normal simulation:

```
def _handle_new_born(self, sim_day: int, cow: Cow, calves_born: List[Calf]) -> None:
    args = {
        "id": self.animal_population.next_id(),
        "breed": AnimalBase.config["breed"],
        "birth_date": sim_day,
        "days_born": 0,
        "p_init": cow.p_gest_for_calf,
        "birth_weight": cow.calf_birth_weight,
    }
    new_calf = Calf(args)
    cow.p_gest_for_calf = 0
    cow.calf_birth_weight = 0
    if not (new_calf.culled or new_calf.sold):
        new_calf.events.add_event(new_calf.days_born, sim_day, animal_constants.ENTER_HERD)
        calves_born.append(new_calf)
    # ... (omitted)
```

When a new calf is born during the normal simulation:

- The calf's breed is set to AnimalBase.config["breed"], which is also derived from the animal.json input file like above. The input from `animal.json` file is saved in `AnimalBase.config` for reuse purposes, rather than retrieving it directly from the input manager.
- The calf's initial phosphorus value (`p_init`) is acquired from the mother cow's `p_gest_for_calf` attribute.
- The calf's birth weight is acquired from the mother cow's `calf_birth_weight` attribute.
- The calf's `birth_date` is set to the current simulation day (`sim_day`). The calf's `days_born` is set to 0. The settings for these two attributes make more sense here.

Like before, during the normal simulation, newborn calves also acquire some attributes from their mother (e.g., initial phosphorus value and birth weight) and some attributes from the animal.json input file (e.g., breed). 

---

The main difference compared to the standalone herd initialization is that the `birth_date` is set to the current simulation day instead of a default value. A desirable but missing feature is to include event descriptions during the herd initialization.

---

### Replacement animals generated during the standalone herd initialization (`herd_factory.py`)

In the herd_factory.py file, the `_heiferIIIs_update()` handles the conversion of a heiferIII to a cow when replacements are needed.

```
def _heiferIIIs_update(self, day: int) -> None:
    # ... (omitted)
    for heiferIII in self.pre_animal_population.heiferIIIs:
        cow_stage = heiferIII.update(0)
        if cow_stage:
            args = heiferIII.get_heiferIII_values()
            args.update(id=self.pre_animal_population.next_id())
            args.update(repro_program=AnimalBase.config["cow_repro_method"])
            args.update(presynch_method=AnimalBase.config["cows"]["presynch_program"])
            args.update(tai_method_c=AnimalBase.config["cows"]["ovsynch_program"])
            args.update(resynch_method=AnimalBase.config["cows"]["resynch_program"])
            cow = Cow(args)
            self.pre_animal_population.cows.append(cow)
            if day >= 3000:
                args.update(id=self.pre_animal_population.next_id())
                replacement_cow = Cow(args)
                self.pre_animal_population.replacement.append(replacement_cow)
    # ... (omitted)
```

Based on this code, when a heiferIII transitions to a cow during the standalone herd initialization (i.e., when replacements are purchased):

- The reproductive program attributes are updated to match the herd inputs from the animal.json file:
    - `repro_program` is set to AnimalBase.config["cow_repro_method"] 
    - `presynch_method` is set to AnimalBase.config["cows"]["presynch_program"]
    - `tai_method_c` is set to AnimalBase.config["cows"]["ovsynch_program"]
    - `resynch_method` is set to AnimalBase.config["cows"]["resynch_program"]

Just an implementation detail: The three attributes `presynch_method`, `tai_method_c`, `resynch_method` are redundant here and to be removed because their values don't need to be stored on each cow. They can be accessed directly whenever we need via `AnimalBase.config`. Anyhow, this doesn't change anything and these repro settings are still acquired from `animal.json`.

If the current simulation day is greater than or equal to 3000, a new replacement cow is created instead and added to the replacement list. The type of replacement animals here is `Cow`.

### Replacements purchased during normal simulation (`life_cycle_manager.py`)

In the `life_cycle_manager.py` file, the method `_check_if_replacement_heifers_needed()` handles the purchasing of replacement heifers during the normal simulation:

```
def _check_if_replacement_heifers_needed(
    self,
    sim_day: int,
    heiferIIIs: List[HeiferIII],
    cows: List[Cow],
    animals_added: List[Cow],
) -> None:
    buy_threshold = 1.01
    while len(cows) + len(heiferIIIs) + self.bought_heifer_num < self.herd_num * buy_threshold and sim_day > 1:
        if len(self.replacement_market) == 0:
            break
        replacement = self.replacement_market.pop(0)
        replacement.events.add_event(replacement.days_born, sim_day, animal_constants.ENTER_HERD)
        replacement.set_p_purchased()
        animals_added.append(replacement)
        self.bought_heifer_num += 1
```

Based on this code, when replacement heifers are needed during the normal simulation:

- Replacements are obtained from the replacement_market list, which contains Cow objects.
- The obtained replacements are added to the animals_added list and the bought_heifer_num counter is incremented.
- The set_p_purchased() method is called on the replacement object, which sets the animal's phosphorus value as a purchased animal.
- An event is added to the replacement's event history to indicate that it entered the herd on the current simulation day.

There is no explicit updating of the replacements' attributes to match the herd inputs from the `animal.json` file during the normal simulation. The replacements retain their original attributes from the replacement_market list.

---

After doing some more digging, I think the main source of problems comes from the inconsistent usage of the two animal types HeiferIII and Cow. Since replacements are now agreed to be heiferIIIs, the repro protocols from input json related to heifers will be applied to the replacement animals. I have a branch `explore-animal-herd-init` where I made the necessary changes for converting from cow replacements to heiferIII replacements in both herd factory and life cycle.

**Comment by jadamchick** [comment]
Thanks for this @ltp23! Very helpful and thorough. It sounds to me like reconciling the heiferIII/cow mismatch will be an important step to ironing things out. 

It would also be very helpful to have: 
1. a list of which attributes **a cow who was purchased as a replacement heifer** will have that are different from the animal.json (i.e. which will she retain for her lifetime, vs. which ones will be updated to match the animal.json (to match the rest of the cows who were born within that herd during the simulation) when she becomes a cow?). 
2. to be able to get a summary of those attributes (at minimum) for the animal_population file being used (so you can know what to expect for the purchased replacements as cows)

Some example attributes that would be helpful to know: 
I assume that Breed and Mature body weight will stay the same for her lifetime (from what you've said above and what I've observed in the simulation). How about the others? 

Breed
Mature body weight
Lactation curve (Wood's) parameters
Do not breed time
Cull milk production 
Repro program + parameters
Culling + death probabilities 

Let me know if you'd like to chat about this sometime! Thanks for digging into things :)

**Comment by ltp23** [comment]
Assuming we have converted all the replacements from cows to heifers (heiferIIIs).

Here are the expected behaviors of the mentioned attributes.

#### Breed

If a replacement heifer is a Holstein, for example, then she will remain a Holstein throughout her lifetime even when she graduates to become a cow. But her calves will have the breed as specified in the animal json.

#### Mature body weight

The mature body weight of a replacement heifer stays the same throughout her lifetime, whereas a newborn calf's mature body weight will be calculated based the two parameters `mature_body_weight_avg` and `mature_body_weight_std`.

#### Lactation curve (Wood's) parameters

Replacement heifers don't carry any information about the actation curve parameters so when they become cows, they will behave exactly like normal cows. This means the parameters under `milking` property in the animal json should apply to both replacement heifers and normal cows.

#### Do-not-breed time

All cows should share the same do-not-breed time from the animal json because they all have shared access to this parameter.

#### Cull milk production and culling/death probabilities

There should be no difference in the behaviors between the starting animals and the animals entering the herd from as replacements.

#### Repro program

Replacement heiferIIIs may have a different repro program than as specified in the animal json. Generally, if they are not already pregnant, their repro programs will be changed to whatever specified by the user.
