### ISSUE TITLE
Flaws in the determination for a fly pen 

### ISSUE THREAD

**Issue by tomhuhh** [RuminantFarmSystems/RuFaS#1534]
While working on the `pilot_testing_Dec2023` and the `Lactation_Curve_Simulations_March` branches, the same error showed up when processing the data from `c2f2`, `c2f12`, and `c2f25` with a regional diet. The error is a key error: Units' was not found in info_map for call call to 'add_variable()'

However, the hotfix provided by Joe @JoeWaddell  in the issue #1531 does not work. It indicates that the pen size of the calf pen needs to be increased, even though the space of the pen (120 stalls, 2x stocking density) is greater than the demand for stalls (89 + 25). 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/ceefd84f-18f2-4073-af48-89d96ccd7a24)

This discrepancy indicated a flaw in the process of determining the need for a fly pen. Further investigation is required.  

## Expected Behavior

No fly pen should be created if the number of stalls is greater than the demand. 

## Current Behavior

KeyError: 'Units' was not found in info_map for call call to 'add_variable()'' even though the number of stalls is sufficient. 

## Steps to Reproduce

1. Go to  the `pilot_testing_Dec2023` or the `Lactation_Curve_Simulations_March` branch. 
2. Update the input path to process data for `c2f2`, `c2f12`, or `c2f25`
3. Simulate for at least one year
4. You should expect to see a KeyError: 'Units' was not found in info_map for call call to 'add_variable()'' even though the number of stalls is sufficient.

**Comment by JoeWaddell** [comment]
The main problem stems from the metadata properties: the max stocking density is set to 2, with a default of 1.2. The max will need to be updated if you want to use a stocking density of 2.5 or 3 (as I've seen on those farms).
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/346b748b-9842-47e2-b68c-177494852119)


Looking at `c2f2`, the math works out (and you can see below from the debugger that the stocking density was corrected to 1.2

![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/cb03d999-4a7c-4fbe-9890-053b31a33e9b)


For the example in the PR description, I see the pen that overflowed as having a number_of_stalls as 80, and since the `max_stocking_density` was 2.5, it was "corrected" to 1.2, so the total of 114 animals does put it over the max number of animals  (80 * 1.2 = 96).

**Comment by tomhuhh** [comment]
Thanks Joe! That makes a lot of sense. I'm closing this issue.
