### ISSUE TITLE
[OM] Allow the option to deduplicate info maps objects

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1560]
Currently, we only have two options to manage the info maps. By default, info maps are included in their entirety along with each variable. We can also switch this off totally by using the `-i` gnu arg flag.

It is also possible to allow a third option that would only keep one copy of an info map object per variable, assuming all the info map objects are identical for that variable.

Suggested option names: NONE, ALL, ONE - or - EXCLUDE ALL, INCLUDE ALL, INCLUDE ONE.

**Comment by Isgotkowitz** [comment]
A possible solution would be to automatically apply this for some fields in the info map, regardless of what users specify.

Some of the fields that only need to be recorded once are class, function, suffix, and prefix. Additionally, while it is possible to record the same variable in different units, it should be considered whether or not this would be an error case.

**Comment by Isgotkowitz** [comment]
After discussion, a different approach will be taken. An option will be added to `add_variable` which allows the calling method to specify whether or not they want all info maps to be recorded for a variable. This option will default to "True", so that all existing calls to "add_variable" can be left undisturbed.
