### ISSUE TITLE
[GH Actions] Adjust and remove the second repo checkout and dependencies installation

### ISSUE THREAD

**Issue by ltp23** [RuminantFarmSystems/RuFaS#1561]
Two of the most time-consuming steps in the GitHub workflows are the repo checkout step and the installation of dependencies.

If there is no easy way to share those two steps between the two jobs - format-code and lint-test-type-check, we may have to combine everything into one big job. 

The expectation is to save about 1 minute every time (from 4.5 minutes down 3-3.5 minutes).

**Comment by Isgotkowitz** [comment]
Consider adding boolean to indicate whether or not Black actually ran in the first job and committed changes. If not, run Mypy, tests, linting etc in the first job, and skip the second.

Would only be beneficial in cases where Black does not change any files, which may not be very often.

**Comment by ew3361zh** [comment]
In reviewing a separate GH Actions PR I came across Github's dependency-caching ability which I think would speed up our actions tremendously if it actually works as advertised. I'm going to bump up the priority on this issue since I think it's worth pursuing.

https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/caching-dependencies-to-speed-up-workflows

**Comment by ew3361zh** [comment]
In PR 1983 I was able to successfully cache the dependencies between jobs.

HOWEVER, this actually increased the time of the GH Action run in total.

I believe this is because we don't actually have any monster dependencies that are taking a long time to download. It's the installation process itself that is taking on average 25 seconds for each job (so a total of 50 seconds per GitHub action run). The installation process isn't affected by caching the dependencies.

Caching and then restoring the cached dependencies actually adds about 6-7 seconds on average.

There may be some other areas of improvements where we could save time in our GitHub actions though. Here are the major time takers in our GitHub Action runs:

Job 1 `format_code`:
`Checkout repository` - 42-44s
`Install dependencies` - 23-26s

Job 2 `lint_test_type_check`:
`Checkout repository` - 42-44s
`Install dependencies` - 23-26s
`flake8` - 12-14s
`Test coverage` - 1m6s-1m8s
`mypy on current branch` - 16-18s
`mypy on dev branch` - 9-10s

The times for `Install dependencies`, `flake8`, `Test coverage`, `mypy on current branch`, and `mypy on dev branch` are all within normal expected range for these processes.

The `Checkout repository` step, though, is a potential for time savings. We currently checkout the repo at a fetch depth of 0 for both jobs. The fetch depth is:

```
In GitHub Actions, the fetch-depth option controls how much of your repository's history is downloaded when you use the actions/checkout action. Here’s a breakdown of what fetch-depth: 0 and fetch-depth: 1 mean and their implications:

fetch-depth: 0
Meaning: Fetch all commit history from the repository, without any limit on how far back it goes.
Use case: Use this if you need the entire commit history for your job, such as for:
Generating changelogs or diffing between commits.
Calculating version numbers based on tags or commit history.
Testing across different commits in CI that require full history.
Time impact: This can significantly increase checkout time, especially for large repositories with long commit histories. The runner will have to download the entire history, which can include thousands of commits and a lot of metadata.
When to use:
When your job relies on the entire history or multiple commits for specific tasks like changelogs or complex git operations.
When you need to work with tags or branches that aren’t included in a shallow clone.
fetch-depth: 1
Meaning: Fetch only the latest commit on the specified branch.
Use case: This is the most common option for CI/CD workflows where you only need the latest code and don't care about the commit history.
Typically used for tasks like testing, linting, or deploying based on the current state of the codebase.
Time impact: Checkout is much faster since only the latest commit and its files are downloaded. This is ideal for most CI workflows where you just need the current state of the codebase.
When to use:
If you don’t need to access the full history, tags, or multiple commits.
For workflows where time efficiency is a priority and commit history is irrelevant.
```

Initial testing of switching our fetch depth to 1 passed fine in the first job (`format_code`) and it shaved the `Checkout repository` time from 43s to 3s (!) but the second job was not able to find the `dev` branch at a fetch depth of 1 by default.

I tried keeping the fetch depth at 1 and then running an explicit step in the second job to fetch the dev branch but it wasn't able to find it.

The simple update for the first job switching to a fetch depth of 1 though will save us about 40 seconds per GH Actions run which seems significant enough.

**Comment by ew3361zh** [comment]
Update:
- Changing the fetch depth to 1 for job 1 of our GH Action does indeed shave ~40 seconds off the `Checkout repository` step but unfortunately that time is added back in (and then some) at the `Get all added or modified files` step. Regardles of what happens earlier, this step needs to fetch dev to be able to compare the state of dev to the state of the feature branch. This checkout takes about 45 seconds (more than what we save at not getting the full `fetch-depth 0` in the `Checkout repository` step).

Having tried to rework this a few different ways, I think the conclusion is:
- Downloading the dependencies doesn't actually take that much time. It's the installation process that takes the time. Therefore caching the dependencies doesn't save any time, it actually adds the few seconds it takes to cache the dependencies.
- The biggest time-eaters in our action are either about on par with what's expected (Installing dependencies, running Pytest, running flake8, running mypy) so there's not really time savings available there.
- We're left with the `Checkout repository` step which does take a good amount of time (~40-45 seconds). It also happens twice - once for each job within the action. However, we need the first job to complete before starting the next job and we can't pass the set-up repository between jobs.
- Additionally, we need the fetch depth of 0 because we're comparing the feature branch to dev to get the changed files for multiple purposes (running Black, making sure there are no unauthorized changes to protected files, and checking if the changelog has been updated).

Therefore, I'm closing this issue and the accompanying PR which has the history of experiments I ran and the resulting Action runs (with times) if anyone would like to investigate further down the line.
