### ISSUE TITLE
[Manure] Rename and refactor `LiquidManurePortionProtocol`

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1618]
**Is your feature request related to a problem? Please describe.**
ManureSeparators currently discharge a single ManureSeparatorDailyOutput which includes both liquid and solid components. It is useful to have them discharged as a single ManureSeparatorDailyOutput (which is a LiquidManurePortionProtocol sub class) for the purposes of passing the output to treatments, separators, and storage (all of which accept LiquidManurePortionProtocols as their inputs)

**Describe the solution you'd like**
It would be helpful and less confusing to have a more generic manure output class. Rename and refactor `LiquidManurePortionProtocol` to something that could include both liquid and solid manure components.

Factors to consider/include with this refactor:
1. Add dry manure components to the base class protocol.
2. Want to be tracking throughout every component (start with must haves, try to do nice-to-haves if it seems manageable or at least write a new issue for implementing tracking for the nice-to-haves if not manageable within this issue):
Manure mass (must-have)
Nutrient composition: N, P, K, C (as volatile solids) (must-have)
Dry matter composition (nice-to-have)
Inorganic components (currently only sand where applicable) (nice-to-have)
3. Differentiate liquid and solid components within this generic manure protocol.
4. Reconcile overlaps between these different versions of the LiquidManurePortionProtocol.
5. Make sure all components can use this new generic protocol (i.e. ensure it still is able to be passed between Separators, Handlers, Bedding, Treatment, and Storage).

**Additional context**
Use this [Manure Component Inputs and Outputs Comparison](https://docs.google.com/spreadsheets/d/1mNphutPFL4OgNG6z3p4x1RY6l_YXbH0Si3WrhGnQ5Ok/edit#gid=0) as a guide to what is currently using the LiquidManurePortionProtocol and what each component tracks in its output and needs for its input.

**Comment by ew3361zh** [comment]
From meeting with Elle:
- In reference to #1786 this should probably be done before proceeding further on issues associated with the branching and merging proposal from Ed and Elle.

**Comment by elle-andreen** [comment]
Additional notes: I think a good option here could be to remove the 'liquid' prefix from manure variables so that all manure objects accept "manure_..." instead of "liquid_manure_..." vs. "solid_manure_..."

At this time, solid manure from a separator for example cannot and is not accepted by any other component, it just "exists" for now. These outputs can be renamed to something like "separated_solid_manure" or similar. 

In manure treatments like composting or CBPB where most outputs are current reported as "solid_manure_..." I think at this time there is no reason these variables cannot also just be called "manure_..." as they would in any other treatment. Any one treatment (storage) will contain one manure mass, and that manure mass should be _either_ liquid or solid, not both, and I don't think there is a reason to explicitly label some treatments' variables as "solid_manure_...".

**Comment by Isgotkowitz** [comment]
Grooming session: `LiquidManurePortionProtocol` will be deprecated and replaced with what is currently being called `ManureStream` as part of the Manure Refresh.
