### ISSUE TITLE
Duplicate the purchased feed emissions reports

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1639]
Currently, there is no connection between the feed storage module and the animal module. We are feeding the animals with the purchased feeds. These feeds have emissions associated with them, which we are computing and reporting to the output manager. We want to duplicate these reports. In other words, instead of computing and reporting once, we want to do it twice. The reason for this is that we are waiting for a new set of inputs to arrive, which have an identical format to the existing inputs. By duplicating the logic, we can substitute a set of inputs once we have them.
* This task needs @KFosterReed review before being closed.
* Consider extracting functions and logic where possible.

**Comment by KFosterReed** [comment]
Thank you for making this issue Pooya! I did not get through my morning tasks in time to get it up before the planning session. To add a bit more context to this, here is a more detailed explanation of why we are doing this:

The current estimates for the emissions associated with the feeds that are purchased by the farm include emissions from several parts of the feed production system: 

1. growing the crops needed for the feed if they are plant based
2. processing the crops or any industry processes associated with non-crop feeds like supplements
3. emissions that are associated with 'land use change'
4. emissions that is sequestered in soil carbon (these are negative emission)

The reason we need to duplicate the emissions report is that we will be getting separate estimates for #3 above, the land use change emissions that are part of the total emissions estimates that we already have. Our FARM-ES partners have a relatively new mandate to report not just the total emissions but also the part of the emissions that are from land use change (and the part of the emissions that are associated with carbon sequestration; however we don't know yet if we will be able to have separate estimates for carbon sequestration). So they would like to recieve a report of the total emissions from purchased feed (which we already have) _and_ a separate report that has only the emissions from the land use change emissions, which we don't yet have. 


For this issue, we would like to: 

1. Duplicate the current 'full_feed_emissions_new.csv' dataset and call it something like 'full_land_use_change_feed_emissions.csv'. 
2. Create a set of outputs that are calculated exactly the same way as the `PurchasedFeedEmissionsEstimator.__init__.purchased_feed_emissions.` but uses the new 'land use change' emissions data inputs instead of the current purchased feed emissions estimates. This output could be called something like `purchased_feed_land_use_change_emissions` if it is not too long. The abbreviation 'LUC' is commonly used for 'land use change' but if we can spell it out, it is probably more clear that way.
