### ISSUE TITLE
[IM][Wiki] Add diagram of IM input validation process

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#1663]
Once issues #1332 and #1333 have been successfully closed, create a diagram of the input validation process and add it to the IM wiki.

This should include:
- nullability
- metadata depth validation
- metadata properties validation
- top level metadata validation
- fixing invalid input data
- fixing array data
- et al

**Comment by ew3361zh** [comment]
@allisterakun @Isgotkowitz can you please review this IM data validation overview? I think I enabled viewing/sharing but Whimsical doesn't let me allow editing or commenting in the document from other people without a paid account.

https://whimsical.com/input-manager-data-validation-overview-T6TuSktxPUYe3BRUURhaDm

**Comment by Isgotkowitz** [comment]
Overall, this diagram looks great Niko - I approve it! I really appreciate the attention-to-detail, the split between complexity and clarity is really great too.

A few things that I think could/should be tweaked:
- `_validate_input_by_type`:
  - In step 3, the diamond at the end of the arrows which contains "Return True" should be a different shape - because this state does not represent a decision.
-  `_array_type_validator`
   - In step 2, the description should be more specifc, like "Checks that the length of the array is valid".
   - In step 3, there are some missing underscores for `_validate_input_by_type()`
   - I think step 4 should be omitted - because `_array_type_validator` does not directly call `_fix_data`.
- `_object_type_validator`
  - I think step 3 should also be omitted here, because `_fix_data` is not directly called by `_object_type_validator`.
  - This method also removes any keys in an input object that are not specified in the metadata properties.

**Comment by ew3361zh** [comment]
> Overall, this diagram looks great Niko - I approve it! I really appreciate the attention-to-detail, the split between complexity and clarity is really great too.
> 
> A few things that I think could/should be tweaked:
> 
> * `_validate_input_by_type`:
>   
>   * In step 3, the diamond at the end of the arrows which contains "Return True" should be a different shape - because this state does not represent a decision.
> * `_array_type_validator`
>   
>   * In step 2, the description should be more specifc, like "Checks that the length of the array is valid".
>   * In step 3, there are some missing underscores for `_validate_input_by_type()`
>   * I think step 4 should be omitted - because `_array_type_validator` does not directly call `_fix_data`.
> * `_object_type_validator`
>   
>   * I think step 3 should also be omitted here, because `_fix_data` is not directly called by `_object_type_validator`.
>   * This method also removes any keys in an input object that are not specified in the metadata properties.

Thank you, @Isgotkowitz, I have addressed each of these points - really appreciate the detailed review!

**Comment by allisterakun** [comment]
Sorry about the delay, I have no issue with the diagram. I think it looks great! Great job Niko!

**Comment by ew3361zh** [comment]
Image has been added to the IM wiki and the Whimsical diagram linked to for more detailed viewing.
