### ISSUE TITLE
Fertilizer Emissions for specific crops

### ISSUE THREAD

**Issue by krb78** [RuminantFarmSystems/RuFaS#1753]
We have worked through a process of aggregating emissions for each specific crop (yay!) but when there are two crops grown in 1 calendar year we had to come up with a solution for handling the emissions. We decided (in June) that we would allocate these emissions by % dry matter. Therefore, if there is a corn silage - triticale double crop and corn silage makes up 90% of the total mass of dry matter harvested off the field, corn silage will receive 90% of the emissions. This is fine logic, except when it comes to emissions associated with synthetic fertilizers. Synthetic fertilizers are applied to a specific crop and all emissions from this fertilizer need to go to the specific crop. In our above example, if nitrogen fertilizer is applied to corn silage but no fertilizer is applied to triticale, all of the emissions associated with the production of that synthetic fertilizer (embedded emissions) should go to corn, not be spread in the 90:10 ratio. 

## Expected Behavior
For synthetic fertilizer applications, they should be associated with a specific crop, not parsed out by % DM. 

## Current Behavior
Currently being allocated across crops by % DM

## Possible Solution
While % DM is a great solution for our other emissions for right now, perhaps using a date cutoff for embedded fertilizer emissions could be a solution. If corn silage is planted on day 135 and harvested on 270 and triticale is planted on 274 and harvest on 130 (of the following year), we could use the date of the fertilizer application (for example 155) to be mean it is for corn silage. There will be some times where it is applied at day 134 (just before planting) which could mess up my idea and the logic :( but I trust someone is smarter than me at this. 

## Context (Environment)
While not the largest portion of our footprints, it is an important one when we grow crops on dairy farms. This would just make us more accurate in our calculations. 

## Possible Implementation
not sure I know the difference between the implementation and the solution :( 

## Target Deadline
by Nov 2024 :)

**Comment by Isgotkowitz** [comment]
@krb78 thank you for writing this up. I have a couple of thoughts I would like to add.

> While % DM is a great solution for our other emissions for right now, perhaps using a date cutoff for embedded fertilizer emissions could be a solution. If corn silage is planted on day 135 and harvested on 270 and triticale is planted on 274 and harvest on 130 (of the following year), we could use the date of the fertilizer application (for example 155) to be mean it is for corn silage. There will be some times where it is applied at day 134 (just before planting) which could mess up my idea and the logic :( but I trust someone is smarter than me at this.

I would like to add a few details to this scenario, because the way emissions are calculated is not exactly as described here. To see the problem more fully, let's consider a two year rotation of corn silage/triticale. In year one, corn silage is planted on day 135 and harvested on day 270, then triticale is planted on 274 and harvested on day 130 of year two. Then corn silage is planted again on day 135 and harvested on day 270, then another triticale planting occurs on day 130. Then year 2 ends.

When deciding how much fertilizer to assign to each harvest, the emissions routines only consider the harvest date of a crop, not the planting date. So in this case, when assigning fertilizer mass to crop harvests, the emissions routines will partition the fertilizer applied in year 2 between the corn silage planted and harvested in year 2 and the triticale that was harvested in year 2 but planted in year 1. This is still problematic, and essentially leads to the same outcome that would be calculated if the fertilizer was divided between the corn silage and triticale that were planted in the same year.

Your idea of assigning all the fertilizer to the crop that is in the field when the application occurs is a good one. In the case that the application occurs before a crop is planted, it would be reasonable to say that the fertilizer is simply assigned to the next crop that is planted in the field.

An alternative solution to consider would be to partition the fertilizer among all harvests that occur _after_ application and _before_ the end of the calendar year.

**Comment by Isgotkowitz** [comment]
Another thing that I would like to mention just so that it doesn't go unnoticed: we keep using the term "calendar year", but we should discuss the specifics of this term when considering what currently happens in RuFaS and what we ultimately want to have happen. More specifically, there is a difference between a calendar year as a period of 365 days vs. everyday in the range [January 1st year _x_, December 31st year _x_].

Right now, the emissions routines are only calculating the emissions from the _last 365 days_ of a simulation. For simulations that start on or before January 1st of a year and end on December 31st of that year, this makes the outcomes no different than if we were looking at the last "calendar year". But I think we will want to switch to calculating the emissions for a "calendar year" as in all the emissions from 2022, etc. Especially when we think about expanding the emissions estimations so that they happen for every year, not just the last.

**Comment by ew3361zh** [comment]
Grooming session:
- @Isgotkowitz to talk with Kaitlyn about edge cases, assigning embedded emissions, come up with specific steps that will be taken to implement this.

**Comment by Isgotkowitz** [comment]
When handling the embedded emissions for synthetic fertilizer applied, they should be assigned to either the next crop planted in the field where fertilizer is applied or to the crop that is already planted where the fertilizer is applied. If the crop to which the emissions are assigned has multiple harvests, the emissions should be split proportionally between all harvests based on their relative dry matter yields. This should be done even if some of the harvests occurred after the fertilizer application.

For example: alfalfa is planted on day 100 of year 1, then harvested on days 145, 185 and 225 of year one and days 120, 160, 200, and 240 of year 2. The dry matter yield of each harvest is 100 kg / ha (dry). Fertilizer is applied on day 160 of year one with total embedded emissions of 70 kg CO2. After assigning and partitioning the emissions, each alfalfa harvest should have 10 kg CO2 emissions associated with it.
