### ISSUE TITLE
Temporary Replacement of Soil N Mineralization Rate factor calculation method with fixed value

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#1810]
The current method to calculate the soil N mineralization rate depends on the C:N ratio of the soil and is calculated with function `calculate_decay_rate_constant` in `mineralization_decomp.py`. The SME team needs to do some more research to determine what the best way to implement the functions that support this method. While this method is being investigated by the SME team, we would like to remove the effect of the soil C:N and soil C:P ratios which is called the `residue_composition_factor`. 

## Status

- The values of the C:N and C:P ratios in layers below Layer 0 are very high (above 2,000 and up to 30,000 in some scenaorios). This causes the residue composition factor to be very small (on the order of 10^-20) which in turn makes the mineralization decay rate to be very very small as well. 

## Intention
 
We want to replace the process based method for the effect of the soil C, N, and P on the decomposition rate factor with a fixed reasonable value while we evaluate the methods that represent this effect . 

- What is the expected outcome?

A N decompositon rate that does not depend on the composition of the soil but still fluctuates with water and temperature

- Why is this change necessary?

The Soil and Crop SME team needs to be able to assess the general accuracy of the mineralization from this soil N pool while we investigate how to represent the effect of soil composition on this process

## Request

The specific requst is the following: 

- In the `mineralize_and_decompose_nitrogen` function in `mineralization_decomp.py`, replace the call to `calculate_nutrient_cycling_residue_composition_factor` with a fixed value of 1 while further evaluation and analysis is completed. 
- Please do not remove the `calculate_nutrient_cycling_residue_composition_factor` method as we hope to re-instate it soon

### Target deadline

Request to be completed by July 31st

**Comment by KFosterReed** [comment]
Hey Dev team, I have been putting off making this issue for some time so forgive the sparsity but I wanted to get up here and will add more detail later

**Comment by PooyaHekmati** [comment]
To be worked on in sprint 19.

**Comment by rawalashmita** [comment]
We could change residue composition factor to a fixed value of 1 while keeping a decay rate as a constant of 0.05 for now. Decay rate has been interchangeably used as mineralization rate while residue composition factor as a composition factor. Can we use the same variable name throughout the code space so that it is easier to follow? 

Similarly, in the code line: root_term = (temp_factor * water_factor) ** 0.5; root term apparently means square root of temperature and water factor while I was under the impression that it is the variable name indicating belowground plant roots. Specific variable name might help in this case if these terminologies mean something specific and different in the soil and crop fields. Just a thought.
