### ISSUE TITLE
[Wiki] Add a comprehensive list of output filter entries

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#1911]
We have different wiki pages for OM, RG, and GG. The information about the possible entries for a filter is spread on these pages. It is difficult for users to know what options are available to them when it comes to working filters. Add a section to OM's wiki page to have a comprehensive list of all possible entries in a filter.

**Comment by Isgotkowitz** [comment]
I think the "Output Filters" section looks good, but there are ways in which it might be improved:
- In the top paragraph where it says "Here is a list of filter options for GraphGenerator and ReportGenerator. More details are available in their respective Wiki pages", links to those wiki pages should be added right there.
- If possible, it would be really great to have the table formatted in a way that doesn't necessitate a scroll bar but this may vary based on a viewer's monitor size.
- If the above point this is not possible, then it might be more useful to have the column order be Entry -> Data Type -> GG -> RG -> Example.
- If the "name" is blank for a report, it will automatically fill in untitled + a timestamp in the column headers. Also graph generator has an equivalent to "name", it is just "title" instead, might be worth trying to fit into the same row cause they essentially do the same thing - or changing the GG to look for "name" instead of "title".
- For "variables", I think it might be better to describe them as lists of keys instead of lists of variables.
- For a lot of the options, GG and RG essentially do the same thing except it winds up in a plot instead of a CSV. Indicating this in the description might make things a little easier to understand.
  - Ex: `filter_by_exclusion` works the same in both RG and GG (I assume), it decides whether variables that match one of the patterns in the filters are included or excluded from the report/plot. But the descriptions read quite differently
- It might be useful to separate the table into multiple: one for GG specific options, one for RG specific options, and another with overlapping options. Although this might just wind up totally regurgitating tables that are already in the RG and GG wiki pages, so maybe it is better to have them altogether.
- Having a separate column for default values/behavior (if applicable) would be nice.

**Comment by ew3361zh** [comment]
Thanks @Isgotkowitz, I was able to address most of these. Great suggestions. The ones I could not figure out a good way to implement:

> If possible, it would be really great to have the table formatted in a way that doesn't necessitate a scroll bar but this may vary based on a viewer's monitor size.

There are too many columns and too much data to be able to do this.

> It might be useful to separate the table into multiple: one for GG specific options, one for RG specific options, and another with overlapping options. Although this might just wind up totally regurgitating tables that are already in the RG and GG wiki pages, so maybe it is better to have them altogether.

I think this would defeat the purpose of having them all together in one place.

**Comment by ew3361zh** [comment]
Wiki has been updated with feedback incorporated: https://github.com/RuminantFarmSystems/MASM/wiki/Output-Manager#output-filters
