### ISSUE TITLE
Make database files threadsafe

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#408]
# Problem
As @JoeWaddell pointed out in #402, running RuFaS in parallel might be problematic. This is because some data files (input JSONs, weather CSVs, etc.) may be accessed by multiple threads simultaneously. To prevent data corruption, steps should be taken to make our databases thread safe (whatever that means).

# Potential solutions
* Perhaps we can just explicitly lock files (read only) before reading from them to ensure that they can't be written to: [StackOverflow link](https://stackoverflow.com/questions/489861/locking-a-file-in-python)
* Perhaps using a database (SQL) format would solve the problem?

Actual computer people likely know much more about this than I do, so that is the extent to which I'm am comfortable making suggestions. 

# Context
I feel strongly having this implemented would greatly benefit sensitivity analyses, validation, or mathematical optimization. So, if it were done before those tasks, it would be very useful.

**Comment by Isgotkowitz** [comment]
I think both solutions are good ones, both have pros and cons.

1. Making files read-only:
  - Pros: this should be easier to implement, would hopefully only require specifying what mode you are opening the file in. In an ideal world you should be able to have multiple processes open the same file in read-only mode at the same time and the OS will be smart enough to allow this because it is inherently thread-safe.
  - Cons: OS' are not always this smart, so it might only allow this to happen after importing a bunch of libraries to ensure thread-safety. Also, it may vary by OS which would increase the time needed to implement a complete solution.

2. Using a database:
  - Pros: this solution would scale better and (ideally) make storage and management of large datasets easier and more standardized. It also puts the burden of thread-safety on the database system that is chosen.
  - Cons: setting up a dedicated database that the entire RuFaS team can use may require a significant amount of dev-hours, and we'll need to take time to get everyone up to speed on how to run the database.

@ all the other computer people, please read this comment carefully and correct anything I said that is wrong, or that you disagree with.

**Comment by Isgotkowitz** [comment]
@JoeWaddell can you share the code you ran that caused issues for you?

**Comment by JoeWaddell** [comment]
> @JoeWaddell can you share the code you ran that caused issues for you?

@Isgotkowitz Here's the crudest version: the first comments explain what works on my system. The latter attempts steps were useful in seeing what crashes, but didn't work. At the very least, you can see my thought process as I worked my way down the script. I'll refrain from posting this code as a proper file for now, since I don't want to confuse folks.

Also, I am of course more than happy to hash these things out in a Zoom meeting, because the files in that folder might be a challenge to understand if you're not using my brain. My plan was to get back to sensitivity analyses once the output manager is fully implemented, so many thanks to Clay for getting it all started up again! 

This requires the setup in the `generate_the_files` script [(found in this folder)](https://github.com/RuminantFarmSystems/MASM/tree/eb5f482300b632c8d52c7f3330276e536114c2c1/model_evaluation/sensitivity_analysis/files_from_joe
), where I generate thousands of input JSONS (modifying the JSON names inside those, as well - so that the starting animal_management_00001.json is set to use animal_management_management_00001.json, and generates the output folder with the suffix 00001...and so forth. 

This code also assumes you use the modified main.py from my local branch, where I allowed it to accept the input filename as an argument. This was prior to @morrowcj adding in the command line argument functionality to master.

```
import main
from joblib import Parallel, delayed, parallel_backend


# simple example of how to structure the runs
# note that the function is in the first parentheses, the variable that goes inside the function in the second
# works find to have a complex variable calculated over the range/loop!
# Example code: Parallel(n_jobs=2)(delayed(sqrt)(i ** 2) for i in range(10))

# NOTE here I was setting the ranges manually, to explore how to divvy up the workload across multiple machines (to further reduce compute time, e.g. PC1 running the first thousand analyses in parallel, PC2 running the next thousand, etc.)
Parallel(n_jobs=2)(delayed(main.main)('animal_management_' + str(i).zfill(5) + '.json') for i in range(516,609)
Parallel(n_jobs=6)(delayed(main.main)('animal_management_' + str(i).zfill(5) + '.json') for i in range(610,650))

# other approaches that didn't pan out
for paralleljobs in range(1,650):
    print(paralleljobs)
    try: main.main('animal_management_' + str(paralleljobs).zfill(5) + '.json')
    except: print(str(paralleljobs) + " failed")

# also no
def tryparallel(paralleljobs):
    try: main.main('animal_management_' + str(paralleljobs).zfill(5) + '.json')
    except: print(str(paralleljobs) + " failed")

Parallel(n_jobs=6)(delayed(tryparallel)(paralleljobs) for paralleljobs in range(160,650))
Parallel(n_jobs=6)(delayed(tryparallel)(paralleljobs) for paralleljobs in range(391,650))

# still no
with parallel_backend('threading', njobs=4):
    for i in range(516,650):
        print(i)
        # inputname = str(SAloopcode) + '_animal_management_' + str(i)
        inputname = 'animal_management_' + str(i).zfill(5) + '.json'
        print(inputname)
        main.main(inputname)
        print('main.main(inputname)')
        print('# main is going to save to the filename specified in the config jsons!')

```

**Comment by morrowcj** [comment]
@JoeWaddell, I'm going to start a SensitivityAnalysis project and add this issue there.

**Comment by morrowcj** [comment]
This may be addressed by the implementation of the new input system #435

**Comment by Isgotkowitz** [comment]
I think this issue can be safely closed, because we are currently able to run RuFaS in parallel without any corruption of data.
