### ISSUE TITLE
Finish FieldManager to connect and execute full SC simulation/routines

### ISSUE THREAD

**Issue by morrowcj** [RuminantFarmSystems/RuFaS#442]
This should be one of the last tasks completed for v1.0 of SC_redesign before merging into master. 

For details, see [the SC redesign design doc](SC_redesign/docs_SC/Admin/design-document_SC-redesign.md), the 
[roadmap](SC_redesign/docs_SC/Admin/road-map_soil-and-crop.md), and possibly [functionality requirements](SC_redesign/docs_SC/Admin/functionality-requirements.md).

Objectives: 
* [ ] Finish/finalize the `Field` class (started in #346), which should run all the daily routines for a given agricultural field. 
* [ ] Create a `FieldManager` class that handles the entire SC simulation through its main method. This class/method should accept a `SCInput` class containing all configuration specifications provided by the 'user'. 
* [ ] Check that all SC methods are being called at the right times and producing reasonable output.
* [ ] Be sure that the *general* functionality of the old code in routines/field/field_management/ is in `Field`.
* [ ] Be sure that the *general*  functionality of the old in routines/field/field.py is in `FieldManager`  

## Associated issues
It may be useful to complete these similar issues in concert with this one:
* #361 
* #159

**Comment by Isgotkowitz** [comment]
This issue has been mostly addressed, the important notes that have not been addressed are that there are still bugs in the new code that produce some incorrect output or are missing some output, and because of this the new module has not been fully/formally evaluated yet. These are specific issues though, and I will be creating more specific issues to track the progress made by them going forward.
