### ISSUE TITLE
Make InputManager error messages clearer

### ISSUE THREAD

**Issue by ew3361zh** [RuminantFarmSystems/RuFaS#635]
When Input Manager is checking the validity of the input data, it would be helpful to note the specific way in which the data failed validation and if the data is not able to be fixed, also note the specific reason why the data was not able to be fixed.

For this issue, error messages in Input Manager `_validate_data()`, `_validate()`, and `_fix_data` should be reviewed and made to be more specific to the errors coming up with the data.

More specificity in the error messages will help the user/developer address the issue.

For V1, it will suffice to provide just a note of which pieces of data weren't valid and whether or not they were able to be fixed.

**Comment by Isgotkowitz** [comment]
Joe will provide examples of current undesirable behavior and desired behavior.

**Comment by JoeWaddell** [comment]
To replicate the error: if I remove one of the `feed_type` patterns nested inside `NRC_Comp_properties` for `NRC_Comp.csv` as follows:
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/35b61be3-bff2-467e-97fd-2b5a9538b141)

The run fails, the message inside the errors file is the following:
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/14fc8511-0b49-49e5-94f9-ab2ce22f58e9)

Then, inside the warnings file, the explanation is: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/b3c555b0-2f6c-4f9b-bf51-62b9e580ecd9)

I think the error message should give a better indication of why data was not valid, and I think the explanation in the warnings (or in both) should give a more specific location for where it fails in metadata. `feed_type` is unfortunately ambiguous, and perhaps should itself be changed so it's unique, but a simple address like: `properties: NRC_Comp_properties: feed_type: pattern` would save time pinpointing errors.  I can see from the previous lines there was a problem with the pattern, but it's a little unclear if the `"InputManager._validate_csv_element.Invalid unfixable element found": {` line is linked to the previous problem, or if it's independent.


In addition, it may be useful to provide the attempted data value, as it does in other cases of the fixable validator errors, if possible. 

Please ask for clarification if this was confusing, or too much of a technical challenge to solve. Still low priority, since I think this is an edge case of what might go wrong (though new entries in the nutrient composition databases may lead to this error in the future, if the user is unfamiliar with ensuring their new entries match existing patterns).
