### ISSUE TITLE
Inputs for methane mitigation supplements

### ISSUE THREAD

**Issue by Ed731551** [RuminantFarmSystems/RuFaS#653]
**This issue is being created to add new variables to the data collection app**, specifically the new inputs required for estimating the mitigation potential (% of reduction in CH4 yield emissions) when feed additives are added to the diet at the recommended doses. CH4 yield refers to methane emissions (g/d) per unit of dry matter intake (DMI). CH4 yield = CH4/DMI, g/kg. 

The documentation needed for implementing this is in the data collection app is available on Basecamp: https://3.basecamp.com/3486446/buckets/5296287/vaults/6283430955 

With the proposed solutions, we need 2 new inputs in the animal json: 

1. "methane_mitigation_method" 
Description: a string that indicates the type of enteric methane mitigation supplement that is fed to the lactating dairy cattle

The acceptable values are: "None"; "3-NOP", "monensin", "essential_oils", "seaweed"; and the default value would be "None".

2.  "methane_mitigation_additive_amount"

Description: a numerical value providing the dosage of the mitigation additive (mg/kg DMI) if a mitigation method is used

The acceptable ranges for monensin and 3-NOP are:
Monensin: 20 to 36 mg/kg DMI
3-NOP: 40 to 100 mg/kg DMI

The dosage default values for them are:

Monensin: 24 mg/kg DMI
3-NOP: 70 mg/kg DMI

We have not yet implemented the essential oil or seaweed additives so for this time the only acceptable input for the dosage for these two inputs should be 0.  

From the subject matter perspective, I can give you my support as much as it is required in order to implement this in the code for the data collection app. Allister, Haowen, please let me know what else is required (i.e., metadata associated with inputs. etc.). Thanks.

**Comment by allisterakun** [comment]
Hey @Ed731551, Where should I place these two new variables? 
Currently, I put those two under "Animal Module" -> "Animal Configuration" -> "General Management" as shown in the screenshot below. Please let me know if they should be moved elsewhere.
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/1bbe9a2f-3d72-454c-91ec-fc318a82fe8b)

P.S. I know the default value is incorrect; I am still trying to figure out if there is a way to implement conditional restriction of the value and default value (depending on what mitigation method is chosen)

**Comment by Ed731551** [comment]
Hi @allisterakun . Many thanks for doing this. 
My understanding is that methane mitigation methods are supposed to be included in manure management as well (as it is set in RuFaS at present). @tomhuhh , could you please confirm that? Thanks.

**Comment by allisterakun** [comment]
> Hi @allisterakun . Many thanks for doing this. My understanding is that methane mitigation methods are supposed to be included in manure management as well (as it is set in RuFaS at present). @tomhuhh , could you please confirm that? Thanks.

Just to clarify, I should include these two variables at the current location (in the "General Management" subsection of the "Animal Configuration" section of the "Animal" module), as well as in the "Manure Management" module. Is this correct?

Can you clarify that by "Manure Management", are you referring to the "Manure Storage and Handling Data" module? Also, where exactly would you want me to put them in the manure management module (under which section, which subsection)?

**Comment by KFosterReed** [comment]
Hi @allisterakun ! Thanks for working on this! I just had a conversation with Edward and we actually don't need the inputs in the manure management module, just in the animal module. Currently the inputs are not nested within the animal configuration but just at the highest level within the 'Animal Module' input json file.

**Comment by KFosterReed** [comment]
![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/0c102dfe-5122-443d-945a-906fd6d4508f)

**Comment by allisterakun** [comment]
> Hi @allisterakun ! Thanks for working on this! I just had a conversation with Edward and we actually don't need the inputs in the manure management module, just in the animal module. Currently the inputs are not nested within the animal configuration but just at the highest level within the 'Animal Module' input json file.

Got it! Will update accordingly!

**Comment by allisterakun** [comment]
Hi @KFosterReed and @Ed731551, I had a conversation with @PooyaHekmati and @ew3361zh about the conditional min-max restriction and the default value for `methane_mitigation_additive_amount`, and I found that it is **impossible** to implement such feature with our current system. Here are some possible solutions:
## Introduce a variable of additive amount for each mitigation method:
For the four mitigation methods ("3-NOP", "monensin", "essential_oils", "seaweed"), we would have a separate variable for each of them: `3NOP_additive_amount`, `monensin_additive_amount`, `essential_oils_additive_amount`, `seaweed_additive_amount`. So that each variable can have its corresponding minimum and maximum restriction, and its corresponding default value.

This would be the best and quickest fix that requires minimum effort.

## Modify the Data Collection App:
We can add a JavaScript file that checks all the conditional restrictions. We have to manually define all the conditions in the file, and it would change the minimum and maximum restrictions, and the default value accordingly.

I'd say this is a halfway janky fix, as we have to manually define every single condition, and things can get very messy.

## Change the IM design, metadata structure, and Data Collection App:
There would be an extra field in the metadata (["conditions"] or something) that indicates what other variable it relates to, and defines the conditions. IM should have the logic to follow the conditions and check the corresponding restrictions. The Data Collection App should also be updated to adapt to this change.

This is the "**ultimate**" solution but requires a lot of effort.

**Comment by tomhuhh** [comment]
Thanks Allister! Sorry for being slow at responding. I was on vacation the last couple days. I'd keep "methane_mitigation_method" and "methane_mitigation_additive_amount" on the same level of "methane_model" in the data collection app. 

Also, in regards to the solutions proposed, the first one makes more sense to me for a quick fix, as long as we can make sure that when a methane mitigation method is selected, others cannot be selected. For example, when a user selects "3-NOP", the boxes for "monensin", "essential oild" and "seaweed" will be greyed out. Thanks!

**Comment by allisterakun** [comment]
> Thanks Allister! Sorry for being slow at responding. I was on vacation the last couple days. I'd keep "methane_mitigation_method" and "methane_mitigation_additive_amount" on the same level of "methane_model" in the data collection app.
> 
> Also, in regards to the solutions proposed, the first one makes more sense to me for a quick fix, as long as we can make sure that when a methane mitigation method is selected, others cannot be selected. For example, when a user selects "3-NOP", the boxes for "monensin", "essential oild" and "seaweed" will be greyed out. Thanks!

Thank you so much for getting back at me!
I currently have the `"methane_mitigation_method"` as a drop-down, so one possible value can be selected.

**Comment by allisterakun** [comment]
> > Thanks Allister! Sorry for being slow at responding. I was on vacation the last couple days. I'd keep "methane_mitigation_method" and "methane_mitigation_additive_amount" on the same level of "methane_model" in the data collection app.
> > Also, in regards to the solutions proposed, the first one makes more sense to me for a quick fix, as long as we can make sure that when a methane mitigation method is selected, others cannot be selected. For example, when a user selects "3-NOP", the boxes for "monensin", "essential oild" and "seaweed" will be greyed out. Thanks!
> 
> Thank you so much for getting back at me! I currently have the `"methane_mitigation_method"` as a drop-down, so one possible value can be selected.

The previous conversation continued as follows:

@tomhuhh clarifies the feature request: 

> For example, when a user selects "3NOP_additive_amount", the boxes for "monensin_additive_amount", “essential_oils_additive_amount” and "seaweed_additive_amount" will be greyed out. 

And my response is:
I believe that I cannot implement that by just modifying the js file. But I did consider the case, and I believe this can be handled within the animal module (if not animal, then the corresponding module).
So all four variables `"3NOP_additive_amount"`, `"monensin_additive_amount"`, `"essential_oils_additive_amount"` and `"seaweed_additive_amount"`  will be passed to the module, and it will decide which one to use based on the `"methane_mitigation_method"` selected. The other three variables will be ignored, so that whatever crazy value they might have would not matter.

**Comment by allisterakun** [comment]
Hi @tomhuhh @Ed731551 @KFosterReed, 
I have wrapped the requested variables (`methane_mitigation_method`, `3NOP_additive_amount`, `monensin_additive_amount`, `essential_oils_additive_amount` and `seaweed_additive_amount`) into a `methane_mitigation` section, which is at the top level of `animal.js`. Please see the screenshots below, and let me know if there are any issues with the current implementation.

![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/f27a7cb1-a4d4-4520-b12f-b6bc07aa14ed)
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/dde1d635-256e-46f2-a913-935a23db7911)

**Comment by tomhuhh** [comment]
I will have the methane mitigation method branch merged early next week. Thanks!
