### ISSUE TITLE
Output Graph Generation

### ISSUE THREAD

**Issue by allisterakun** [RuminantFarmSystems/RuFaS#777]
It has been brought to our attention that all the output graphs are omitted following the depreciation of the old OutputHandler in #739. I propose creating a new GraphGeneration class to implement the graph generation feature. 
- Reason to create a new class
  - Instead of hard-coding all the graph information as the old OutputHandler Graphics.py, we want to create a more general tool with its own purpose of graph generation.
- GraphGeneration
  - This class would expect a json file containing all the necessary information as input, and use it to generate the desired graph. Each generated graph should have a corresponding json file containing the following:
    - Graph Type (line graph, dot plot, bar graph, pie chart, etc.)
    - All the variables needed to generate the graph
    - Other information (title, x-axis and y-axis label, legends, x-axis and y-axis ranges): all other information here is optional.
  - This class would have a separate method for generating different types of graphs, for example:
    - `_generate_line_graph()`
    - `_generate_bar_graph()`
    - `_generate_dot_graph()`
    - `_generate_pie_graph()`
  - This class would have a `generate_graph()` method that 
    - takes in the json information file as input
    - calls the `_filter_variables_pool()` in OM to get all the necessary variables for graph generation
    - routes to the corresponding method according to the graph type
- Please provide:
  - A list of graphs that need to be generated
  - For each graph, please provide a json file containing:
    - Graph Type (line graph, dot plot, bar graph, pie chart, etc.)
    - All the variables needed to generate the graph
    - Other information (title, x-axis and y-axis label, legends, x-axis and y-axis ranges): all other information here is optional.

**Comment by PooyaHekmati** [comment]
> It has been brought to our attention that all the output graphs are omitted following the depreciation of the old OutputHandler in #739. I propose creating a new GraphGeneration class to implement the graph generation feature.

Let's call it GraphGenerator.
> 
> * Reason to create a new class
>   
>   * Instead of hard-coding all the graph information as the old OutputHandler Graphics.py, we want to create a more general tool with its own purpose of graph generation.

We want to have a dedicated class for this because it falls outside of the domain of responsibility of the Output Manager. Following the same reasoning in both Input and Output Managers, this new class should be agnostic about user preferences.

> * GraphGeneration
>   
>   * This class would expect a json file containing all the necessary information as input, and use it to generate the desired graph. Each generated graph should have a corresponding json file containing the following:

It shouldn't expect a json file, that is outside of its domain. In output manager, in save_variables() we have already read and parsed the filter files. That logic can be reused. Right now we have _load_txt_file_to_list() to read the filter files, with the proposed json structure, this function can be upgraded to be able to handle jsons as well.

>     
>     * Graph Type (line graph, dot plot, bar graph, pie chart, etc.)
>     * All the variables needed to generate the graph
>     * Other information (title, x-axis and y-axis label, legends, x-axis and y-axis ranges): all other information here is optional.

You probably can use dictionary comprehension here to make it future-proof.
>   * This class would have a separate method for generating different types of graphs, for example:
>     
>     * `_generate_line_graph()`
>     * `_generate_bar_graph()`
>     * `_generate_dot_graph()`
>     * `_generate_pie_graph()`

"Generation" is already in the class name, do we need to repeat it in the function names? I.e., GraphGenerator._generate_line_graph() vs GraphGenerator._line_graph() .
>   * This class would have a `generate_graph()` method that
>     
>     * takes in the json information file as input
>     * calls the `_filter_variables_pool()` in OM to get all the necessary variables for graph generation
>     * routes to the corresponding method according to the graph type

No, this will lead to circular dependencies. Instead, in OM.save_variables() we first read and parse the filters, then we call _filter_variables_pool() to get the intended subset of variables. then we call the right function to handle those (json, csv, png).

> * Please provide:
>   
>   * A list of graphs that need to be generated
>   * For each graph, please provide a json file containing:
>     
>     * Graph Type (line graph, dot plot, bar graph, pie chart, etc.)
>     * All the variables needed to generate the graph

We don't need all the variables, we need filters that match with the desired variables.
>     * Other information (title, x-axis and y-axis label, legends, x-axis and y-axis ranges): all other information here is optional.
