### ISSUE TITLE
Daylength values are hardcoded

### ISSUE THREAD

**Issue by Isgotkowitz** [RuminantFarmSystems/RuFaS#881]
The lengths of days are calculated based on the average daylengths of each month in Madison, WI. They should be specific to the location being simulated by RuFaS.

## Expected Behavior

Daylengths calculated should be specific to the location being simulated in RuFaS.

## Current Behavior

Daylengths are calculated based on the average daylength of each month in Madison, WI. See the method `determine_daylength` in `current_day_conditions.py` for details.

## Possible Solution

- Pull the latitude from one of the field inputs, and use it to calculate the daylength for any given day (most appropriate solution for v1).
- Make the daylength of each day an input (more appropriate for a future version of RuFaS).

## Possible Implementation

Use equation 1:1.1.6 from the [SWAT Theoretical Documentation](https://swat.tamu.edu/media/99192/swat2009-theory.pdf)

**Comment by PooyaHekmati** [comment]
After talking with Kristan and Kaitlyn about this, I can confirm that equation 1:1.1.6 from the [SWAT Theoretical Documentation](https://swat.tamu.edu/media/99192/swat2009-theory.pdf) is what we want to do here. The reason is that 1) it reduces the number of inputs, 2) it is consistent with the rest of SWAT.
