### ISSUE TITLE
Error created when running manure scenario that uses the rotary screen

### ISSUE THREAD

**Issue by KFosterReed** [RuminantFarmSystems/RuFaS#906]
## Current Behavior

A certain combination of manure management practices and pen assignments is resulting in the following error: 

![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/64a936d0-787e-4f78-9cc4-a316e094b28a)

## Steps to Reproduce

1. On the Main branch if you change the first manure scenario to the following: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/9a7b8615-942f-44f5-9618-12a051bf8f80)
and add that manure scenario to the Growing pen (pen 1) in the default_animal.json and run the default_metadata it will produce this error
2.
3.
4.

## Context (Environment)

The manure scenario outlined above is one of the management practices used by our pilot testing farms and we need to be able to simulate it.

**Comment by harry-samuels** [comment]
I've done some digging on this bug and I believe that I have at least located the point at which the bug becomes readily apparent.

Firstly, I noticed that issue actually seems to be tied to the **'"manure_treatment": "anaerobic lagoon"'** section of the input file. I was able to produce this same error when using the default metadata, only changing the manure scenario of the GROWING pen to be scenario 0 and the CALF pen to use scenario 1 before making changes to scenario 0 in the manure_management.json input file.

The error occurred when the manure management scenario described by Haowen was used on the GROWING pen or the CLOSE_UP pen, but not when used as the manure management scenario for the CALF pen or the LAC_COW pen. The error also occurred when the problem scenario was scenario #1 instead of #0.

The error occurred with multiple different "manure_separator" inputs (but not all of them),  multiple "bedding_type" inputs, and multiple "manure_handler" inputs (but not all). The occurrence of the error would change depending on the chosen "manure_separator" and "manure_handler", sometimes switching between erroring and not erroring by just changing one of them. A full list of error inducing and non-error inducing test scenarios I used for the GROWING pen is listed at the bottom of this thread. 

The error appears to occur in **manure_separator_daily_outup.py** in the __post_init__() function when **self.total_daily_manure_volume is less than self.final_solids_wet_mass_volume**. This leads to a negative value for self.final_daily_volume which then leads to a negative value for self.liquid_manure_daily_volume, ultimately causing the error message shown above.

I am not sure how the values for self.total_daily_manure_volume and self.final_solids_wet_mass_volume are supposed to be calculated so I am unable to determine which one is being calculated incorrectly.


**List of Tested Scenarios:**

**Caused Error:**

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "sand lane",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "other",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "Sand",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "alley scraper",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "tillage",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

 {
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "harrowing",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "harrowing",
      "manure_separator": "screw press",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "Sand",
      "manure_handler": "harrowing",
      "manure_separator": "screw press",
      "manure_treatment": "anaerobic lagoon"
    },

**No Error:**

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "screw press",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "none",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "slurry storage outdoor"
    },


{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "slurry storage underfloor"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "open lots"
    },


{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "compost bedded pack barn"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic digestion"
    }, 

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "flush system",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },


{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "alley scraper",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

{
      "scenario_id": 0,
      "bedding_type": "manure solids",
      "manure_handler": "manual skid steer scraping",
      "manure_separator": "rotary screen",
      "manure_treatment": "anaerobic lagoon"
    },

**Comment by KFosterReed** [comment]
Thanks for the sleuthing Harry! It seems like there may be some issues with the mass balance tracking to look into... Great information to follow up on :)

**Comment by tomhuhh** [comment]
Thanks @harry-samuels! 

I was able to repeat the error with the exact same combination of methods listed by Loi. 

Thank you for putting together a list of combinations that caused the same error. 

I think this is definitely a great starting point for troubleshooting this issue. 

Thanks!
Haowen

**Comment by PooyaHekmati** [comment]
@KFosterReed How severe is the impact of this issue? Can we raise an error or warning when it happens as a temporary solution for now and revisit it when we have more bandwidth, or is it a burning priority that needs to be fixed asap?

**Comment by KFosterReed** [comment]
So, the important thing is not so much the combination of the manure management scenarios that cause an error. The important problem here is that we are predicting negative manure somewhere along the line. This error is flagged when the virtual manure has been passed from the ManureHandler to the ReceptionPit to the ManureSeparator to the Manure Treatment protocol. With Niko and Ed, we have recently identified some corrections to how mass conversions are handled in the manure module but my guess is there might be more if this is still happening. Anyone who has bandwidth and feels like they have a good grasp on unit conversions (not sure how else to describe it... Mass Balance? Physics?) that can take a look at the manure handler, reception pit and separator codes might be able to identify some of the root causes of this error

**Comment by ltp23** [comment]
Thanks Kristan for the update on the progress on that. After crunching some numbers, I noticed one small tweak that seems to be working for me is to adjust the `percent_dry_solids` to be greater than equal to the `total_solids_removal_efficiency_for_separator`.

**Comment by ew3361zh** [comment]
This comment is happening at the dev-team meeting:

Loi will explain why this issue is being moved to Blocked status.

**Comment by ltp23** [comment]
Thanks Niko. Maybe one of the SME's can come up with an acceptable workaround for this issue and then I can implement it.

**Comment by Isgotkowitz** [comment]
In planning meeting: @KFosterReed seeking your guidance on how to unblock this issue, either by giving direction or giving us someone to speak with.

**Comment by KFosterReed** [comment]
I am going to close this issue. I can't recreate it anymore and believe that we may have fixed it in the TAN PR that Niko pushed last month :)
