### ISSUE TITLE
Exception handling across the codebase

### ISSUE THREAD

**Issue by PooyaHekmati** [RuminantFarmSystems/RuFaS#908]
@allisterakun Please fill in the details here.

**Comment by allisterakun** [comment]
The exception handling in RuFaS can be improved. 
## Current Behavior

Currently, when RuFaS encounters an exception during simulation, the default Python exception handler terminates the simulation and raises the exception without generating any output or logs through OutputManager. This lack of information makes it difficult to diagnose errors, especially those not present in the function logic of the main execution thread, as they don't appear in the exception's traceback.

## Expected Behavior
The system should be designed to ensure that upon encountering an exception, OutputManager dumps all logs and data pools before the program exits. Additionally, relevant system and execution context information should also be captured for debugging purposes.

## Steps to Reproduce
This is just an example that demonstrates how the current exception-handling method can be no help when figuring out an issue. 
1.
2.
3.
4.

## Context (Environment)
The issue can be observed when the input data triggers an exception, but the generated exception message lacks information. 

## Possible Implementation
Consider introducing a custom ExceptionHandler class to replace Python’s default exception handler. This custom handler would be designed to intercept all exceptions, perform a comprehensive dump of OutputManager data, and log additional context before the program's execution stops.

**Comment by ltp23** [comment]
## Proposed Solution:

Wrap the main entry function with a try/catch block. When an exception happens, report it to the OM error pool, create the error log file, and then terminate. Consider log verbosity to determine if a call to `sys.stdout.write()` is needed.
