### ISSUE TITLE
Negative daily milk produced 

### ISSUE THREAD

**Issue by jadamchick** [RuminantFarmSystems/RuFaS#918]
Cow.milking_update.milk_data_at_milk_update.estimated_daily_milk_produced has negative values for a small portion of cow-days (eg 6 rows out of 112505) 

## Expected Behavior

Milk production is expected to always be greater than or equal to zero. 

## Current Behavior

There are values for daily milk produced that are less than zero (I have seen as far negative as -2 kg). 
It seems to occur when I change the cull_milk_production value on the animal input json to 0.

## Steps to Reproduce

1. Run simulation with default animal inputs, except with cull_milk_production_value to 0. 
2. Use output filter ^Cow.milking_update.*
3. Open CSV and sort rows by Cow.milking_update.milk_data_at_milk_update.estimated_daily_milk_produced (smallest to largest)
4. Negative values show in the top several rows 

## Context (Environment)

Implies something is off with the milk production values. Maybe they just need to be truncated at zero, or maybe there is something more foundational.

**Comment by JoeWaddell** [comment]
So I think I've pinpointed where this is coming from:

In `cow.py` there is this block of code:

        estimated_daily_milk_produced = self.calculate_daily_milk_produced()

        if estimated_daily_milk_produced > 0.0:
            daily_milk_variation = self.determine_param_value(AnimalModuleConstants.DAILY_MILK_VARIATION_MEAN,
                                                              AnimalModuleConstants.DAILY_MILK_VARIATION_STD_DEV)
            estimated_daily_milk_produced += daily_milk_variation

Note the final line: when the variation is negative and greater than `estimated_daily_milk_produced`, it'll result in a negative value. The quickest fix would be to add logic to a subsequent line, 
e.g. where it says:
`self.estimated_daily_milk_produced = estimated_daily_milk_produced`
update to: 
`self.estimated_daily_milk_produced = max(0, estimated_daily_milk_produced)`

I can make a quick PR if this proposed fix sounds good to @YijingGong and @tomhuhh , since they have been working on lactation curve improvements.

EDIT: To clarify a little more, I want to be sure that the reduction to 0.0 makes sense, because we could also simply not apply the variation value in the cases where it would reduce it to/past 0.0. Depends a little on how exactly we should conceptualize the variation value.

**Comment by tomhuhh** [comment]
Thanks Julie! Thanks Joe! I ran the simulation on the main branch but could not repeat the issue. One thing I would check when working with this data is that the data is filtered based on whether the animal is lactating (i.e. 'Cow.milking_update.milk_data_at_milk_update.lactating' = TRUE). If that is the case, and there is still negative values when cull_milk_production_value is set to 0, then I think the solution proposed by Joe makes sense to me. Also, how likely is it in reality that the cull_milk_production_value is 0? Thanks!

**Comment by YijingGong** [comment]
Interesting point, Joe. I never thought of setting the 'cull_milk_production' to 0. And I never paid attention to the end of the lactation curve (I usually only focus on the first 305 days). So I tested a little bit. Below is a lactation curve that I plotted according to the parity 3+ lactation curve parameters currently in the main branch. 

<img width="653" alt="Screenshot 2023-11-08 at 3 36 49 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/51036031/b7129d5c-b5aa-4d11-b1f6-b0d15084c255">

You can see even with the parity 3+ group (the persistence is low compared to parity 1 and 2), on average, they still have around 4 kg of milk produced at DIM = 1000. With the current constants of milk variation: 
`DAILY_MILK_VARIATION_MEAN = 0
    """Mean of the daily milk production variation from the estimated milk production, kg/day"""`

   ` DAILY_MILK_VARIATION_STD_DEV = 1.0
    """Standard deviation of the daily milk production variation from the estimated milk production, kg/day"""`
It should be very hard to see a negative milk production even at day 1000. So I would be a little bit concerned about why we got the negative milk production. One reason I could think of is that because you set the 'cull_milk_production' to 0, which is basically saying never cull a cow because of production reasons. So if some cows are labelled "do_not_bred" (which means they will never get pregnant and enter the next lactation), and they are super healthy (which means they will not get culled because of the health issue), then they will always stay in the herd and try to produce milk till the end (like DIM = 2000 or something). At that point, the milk production may be negative (due to the variation that we add). Thinking through this scenario, I really think it is not a good input to set 'cull_milk_production' to 0.

**Comment by jadamchick** [comment]
Thanks everyone! I think you are right about the variation being the source, and it makes sense that it is only happening with very few days on very few animals. 
I hear your point on not setting that value to zero on a regular basis. I'm doing it in this case because we are trying to recreate a specific set of animals through several lactations, as opposed to a herd that maintains a specific structure, and I want to control their culling based on statistical event frequencies instead of process-based (repro/production) to see how closely I could recreate the real herd dynamics. 
I realize that isn't a very realistic scenario, but wanted to make sure it wasn't unmasking a more significant issue. Thanks for the quick work!! 

ps- here is a screen shot of one of the output files w/negative values, sorry not to provide it earlier. Just to give a bit more context on the animals/days with those values (file is sorted by millk, smallest to largest): 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/f13bf337-8dd5-4b77-936a-37736329868a)

**Comment by JoeWaddell** [comment]
Thanks @tomhuhh and @YijingGong!

It happens when there is an exceptionally large milk_variation value, since even with an SD of 1, those will happen occasionally. I found it happening with `daily_milk_variation` values of -3.18, -2.56, -2.17, etc. Likewise the cows were indeed mostly parity 3+ and over 1k days in milk.  
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/cdd3743b-88de-4080-82e3-17843221f9b4)


For the reasons you both mentioned, it's so rare that it's unlikely to ever happen, but regardless we could add the quick fix just to ensure we never get negative milk values fouling data further downstream.

**Comment by YijingGong** [comment]
Interesting, & make sense haha
I think I underestimated how far a normal distribution of mean=0 and sd = 1. But thinking that if we have 1000 cow, and simulation for 1000 day, then it is 1,000,000 times the program need to draw from the normal distribution. Even though there is only 0.013% probability of going beyond -3, 0.013% times one million is 130. 

<img width="846" alt="Screenshot 2023-11-08 at 4 16 03 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/51036031/fce2d5a8-18e7-46ec-80f2-a95e889f4255">

**Comment by KFosterReed** [comment]
LOVE this conversation! Great work all around!!! 
@jadamchick congrats on your first time breaking the model! Here's to many more!!
@JoeWaddell Excellent work pinpointing an efficient solution!
@tomhuhh and @YijingGong Really awesome exploration of the problem and context. 

This may sound strange because this is about finding a bug in the model but I find this super encouraging for a number of reasons not the least of which is how quickly you were able to address! Thanks team!
